all:
  javascripts: [/liTinymcePlugin/tiny_mce,duration]
  stylesheets: [manifestation]

indexSuccess:
  stylesheets: [event-list, list-print: {media: print}, gauge-small]
  javascripts: [list-scroll, event-list, gauge-small]
newSuccess:
  stylesheets: [view,event,/private/event.css]
  javascripts:  [event]
createSuccess:
  stylesheets: [view,event,/private/event.css]
  javascripts:  [event]
updateSuccess:
  stylesheets: [view,event,checkpoint,/private/event.css]
  javascripts:  [event,checkpoint]
editSuccess:
  stylesheets: [view,event,checkpoint,/private/event.css]
  javascripts:  [event,checkpoint]
showSuccess:
  stylesheets: [view,event,/private/event.css]
  javascripts:  [event]

