default:
  javascripts: [menu, /sfFormExtraPlugin/js/jquery.autocompleter.js, /cxFormExtraPlugin/js/cx_open_list.js, geo-street-base?<?php echo date('Ymd') ?>, helper, jquery.maskedinput.js]
  stylesheets: [contact]

<?php echo sfConfig::get('app_options_design',false) && sfConfig::get(sfConfig::get('app_options_design').'_active') ? '_'.sfConfig::get('app_options_design').'/' : '' ?>
createSuccess:
  stylesheets: [view<?php if ( sfConfig::get('app_options_design',false) && sfConfig::get(sfConfig::get('app_options_design').'_active') ): ?>, /private/rp-tdp.css, default-input-info<?php endif ?>]
  javascripts: [contact-edit, autocomplete-setnull<?php if ( sfConfig::get('app_options_design',false) && sfConfig::get(sfConfig::get('app_options_design').'_active') ): ?>, default-input-info<?php endif ?>]
<?php echo sfConfig::get('app_options_design',false) && sfConfig::get(sfConfig::get('app_options_design').'_active') ? '_'.sfConfig::get('app_options_design').'/' : '' ?>
newSuccess:
  stylesheets: [view<?php if ( sfConfig::get('app_options_design',false) && sfConfig::get(sfConfig::get('app_options_design').'_active') ): ?>, /private/rp-tdp.css, default-input-info<?php endif ?>]
  javascripts: [contact-edit, autocomplete-setnull<?php if ( sfConfig::get('app_options_design',false) && sfConfig::get(sfConfig::get('app_options_design').'_active') ): ?>, default-input-info<?php endif ?>]
<?php echo sfConfig::get('app_options_design',false) && sfConfig::get(sfConfig::get('app_options_design').'_active') ? '_'.sfConfig::get('app_options_design').'/' : '' ?>
updateSuccess:
  stylesheets: [view<?php if ( sfConfig::get('app_options_design',false) && sfConfig::get(sfConfig::get('app_options_design').'_active') ): ?>, /private/rp-tdp.css, default-input-info<?php endif ?>]
  javascripts: [contact-edit, autocomplete-setnull<?php if ( sfConfig::get('app_options_design',false) && sfConfig::get(sfConfig::get('app_options_design').'_active') ): ?>, default-input-info<?php endif ?>]
<?php echo sfConfig::get('app_options_design',false) && sfConfig::get(sfConfig::get('app_options_design').'_active') ? '_'.sfConfig::get('app_options_design').'/' : '' ?>
editSuccess:
  stylesheets: [view<?php if ( sfConfig::get('app_options_design',false) && sfConfig::get(sfConfig::get('app_options_design').'_active') ): ?>, /private/rp-tdp.css, default-input-info<?php endif ?>]
  javascripts: [contact-edit, autocomplete-setnull<?php if ( sfConfig::get('app_options_design',false) && sfConfig::get(sfConfig::get('app_options_design').'_active') ): ?>, default-input-info<?php endif ?>]
<?php echo sfConfig::get('app_options_design',false) && sfConfig::get(sfConfig::get('app_options_design').'_active') ? '_'.sfConfig::get('app_options_design').'/' : '' ?>
showSuccess:
  stylesheets: [view<?php if ( sfConfig::get('app_options_design',false) && sfConfig::get(sfConfig::get('app_options_design').'_active') ): ?>, /private/rp-tdp.css, default-input-info<?php endif ?>]
  javascripts: [contact-show<?php if ( sfConfig::get('app_options_design',false) && sfConfig::get(sfConfig::get('app_options_design').'_active') ): ?>, contact-edit, autocomplete-setnull, default-input-info<?php endif ?>]

<?php echo sfConfig::get('app_options_design',false) && sfConfig::get(sfConfig::get('app_options_design').'_active') ? '_'.sfConfig::get('app_options_design').'/' : '' ?>
indexSuccess:
  javascripts: [rp-list, list-scroll, integrated-search]
  stylesheets: [print-list: {media: print}, contact-list, batch-actions,<?php if ( sfConfig::get('app_options_design',false) && sfConfig::get(sfConfig::get('app_options_design').'_active') ): ?>, /private/rp-tdp.css, default-input-info<?php endif ?>]
<?php echo sfConfig::get('app_options_design',false) && sfConfig::get(sfConfig::get('app_options_design').'_active') ? '_'.sfConfig::get('app_options_design').'/' : '' ?>
duplicatesSuccess:
  javascripts: [rp-list, contact-duplicates]
  stylesheets: [print-list: {media: print}, contact-list, batch-actions]
<?php echo sfConfig::get('app_options_design',false) && sfConfig::get(sfConfig::get('app_options_design').'_active') ? '_'.sfConfig::get('app_options_design').'/' : '' ?>
filterSuccess:
  javascripts: [rp-list]
  stylesheets: [print-list: {media: print}, contact-list, batch-actions]
<?php echo sfConfig::get('app_options_design',false) && sfConfig::get(sfConfig::get('app_options_design').'_active') ? '_'.sfConfig::get('app_options_design').'/' : '' ?>
sideBarSuccess:
  layout: nude
<?php echo sfConfig::get('app_options_design',false) && sfConfig::get(sfConfig::get('app_options_design').'_active') ? '_'.sfConfig::get('app_options_design').'/' : '' ?>
filtersSuccess:
  layout: nude

<?php echo sfConfig::get('app_options_design',false) && sfConfig::get(sfConfig::get('app_options_design').'_active') ? '_'.sfConfig::get('app_options_design').'/' : '' ?>
labelsSuccess:
  has_layout: false
  <?php if ( sfConfig::get('app_options_design',false) && sfConfig::get(sfConfig::get('app_options_design').'_active') ): echo PHP_EOL; ?>
  http_metas:
    content-type: application/pdf; charset=utf-8
  <?php endif; echo PHP_EOL; ?>
<?php echo sfConfig::get('app_options_design',false) && sfConfig::get(sfConfig::get('app_options_design').'_active') ? '_'.sfConfig::get('app_options_design').'/' : '' ?>
csvSuccess:
  has_layout: false
  http_metas:
    content-type: text/comma-separated-values
    content-disposition: attachment; filename=contacts-list.csv

<?php //echo sfConfig::get('app_options_design',false) && sfConfig::get(sfConfig::get('app_options_design').'_active') ? '_'.sfConfig::get('app_options_design').'/' : '' ?>
cardParams:
  javascripts: [rp-card, rp-member-card-seat]
  stylesheets: [rp-card]
cardSuccess:
  stylesheets: [/sfAdminThemejRollerPlugin/css/reset.css: {media: all}, contact-card: {media: all}, /private/contact-card: {media: all}]
  javascripts: [-menu]
cardSelling:
  stylesheets: [/sfAdminThemejRollerPlugin/css/reset.css: {media: all}, contact-card: {media: all}, /private/contact-card: {media: all}]
  javascripts: [-menu]  
<?php echo sfConfig::get('app_options_design',false) && sfConfig::get(sfConfig::get('app_options_design').'_active') ? '_'.sfConfig::get('app_options_design').'/' : '' ?>
cardSuccessAndPay:
  stylesheets: [/sfAdminThemejRollerPlugin/css/reset.css: {media: all}, contact-card: {media: all}, /private/contact-card: {media: all}]
  javascripts: [-menu]

vcfSuccess:
  has_layout: false
  http_metas:
    content-type: text/vcard
    content-disposition: attachment; filename=contact.vcf
            
ajaxSuccess:
  has_layout: false
  http_metas:
    content-type: application/json
        
