generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Organism
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          organism
    with_doctrine_route:   true
    actions_base_class:    sfActions
    extra:                 [show]

    config:
      actions: ~
      fields:
        name:       { label: Name }
        address:    { label: Address }
        postalcode: { label: Postal code }
        city:       { label: City }
        email:      { label: Email }
        npai:       { label: Has moved }
        country:    { label: Country }
        Category:   { label: Category }
        organism_category_id { label: Category }
        created_at: { label: Created at }
        updated_at: { label: Updated at }
        description: { label: Description }
        url:        { label: URL }
      list:
        title: Organisms list
        display: [Category, name, address, postalcode, city, email, npai]
      filter:
        display: [name, postalcode, city, country, email, npai, organism_category_id]
      show:
        display:
          NONE: [_show_who, _show_email, _show_phonenumbers_list]
          Address:  [name, address, postalcode, city, country]
          Internet: [email, url]
          Precisions: [npai, description]
          Details: [created_at,updated_at,slug,longitude,latitude]
      form:
        display:
          NONE:  [name, address, postalcode, city, country]
          Internet: [email, url]
          Precisions: [npai, description]
          Phonenumbers: [_form_phonenumbers_list]
      edit:
        title: Organism %%name%%
      new:
        title: New organism
