# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  javascripts:    [menu,organism]

updateSuccess:
  stylesheets: [view]
  javascripts: [more-simple]
newSuccess:
  stylesheets: [view]
  javascripts: [more-simple]
editSuccess:
  stylesheets: [view]
  javascripts: [more-simple]
showSuccess:
  stylesheets: [view]
  javascripts: [more-simple]
