generator:
  class: sfDoctrineGenerator
  param:
    model_class:           SeatedPlan
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          seated_plan
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:
        _edit:
          credentials: event-seated-plan-edit
        _new:
          credentials: event-seated-plan-new
        _batchDelete:
          credentials: event-seated-plan-del
        _delete:
          credentials: event-seated-plan-del
      fields:
        seat_diameter:
          label: Plot diameter behind a seat
          help: px
        background:
          label: Background color
          help: HTML colors
        list_nb_seats:
          label: Size
          type: number
      list:
        display: [Location, Workspace, _list_nb_seats, description]
        table_method: retreiveOrderedList
        sort: ['l.name, w.name', '']
        object_actions:
          _edit: ~
          _delete: ~
      filter:
        display: [location_id, workspace_id, _list_nb_seats, background]
      form:
        display:
          General: [location_id, workspace_id, description, _show_nb_seats]
          Plan:    [seat_diameter, background, Picture, _show_picture, _form_picture_del]
      edit:    ~
      new:     ~
      show:
        display: [_show_raw_picture]
