generator:
  class: sfDoctrineGenerator
  param:
    model_class:           SeatedPlan
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          seated_plan
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        seat_diameter:
          label: Plot diameter behind a seat
          help: px
        background:
          label: Background color
          help: HTML colors
      list:
        display: [Location, Workspace, description]
        table_method: retreiveOrderedList
      filter:
        display: [location_id, workspace_id, background]
      form:
        display:
          General: [location_id, workspace_id, description]
          Plan:    [seat_diameter, background, Picture, _show_picture, _form_picture_del]
      edit:    ~
      new:     ~
