generator:
  class: sfDoctrineGenerator
  param:
    model_class:           PaymentMethod
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          payment_method
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        member_card_linked: { label: "Linked w/ MC ?", credentials: [tck-admin-member-cards] }
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
