all:
  javascripts: [/liTinymcePlugin/tinymce.min.js, /liTinymcePlugin/jquery.tinymce.min.js, email]
  stylesheets: [email]

contentSuccess:
  has_layout: false

indexSuccess:
  javascripts: [list-scroll]
  stylesheets: [print-list: {media: print}]

uploadSuccess:
  javascripts: [-/liTinymcePlugin/tinymce.min.js, -/liTinymcePlugin/jquery.tinymce.min.js]
