default:
  javascripts: [menu,/sfFormExtraPlugin/js/jquery.autocompleter.js]

updateSuccess:
  stylesheets: [view]
newSuccess:
  stylesheets: [view]
editSuccess:
  stylesheets: [view]
  javascripts: [contact-edit]
showSuccess:
  stylesheets: [view]
  javascripts: [contact-show]

indexSuccess:
  javascripts: [contact-filters]
filterSuccess:
  javascripts: [contact-filters]


#csvSuccess:
#  has_layout: off
#  http_metas:
#    content-type: application/msexcel
#    content-disposition: attachment; filename="contacts-view.csv"
