default:
  javascripts: [menu,/sfFormExtraPlugin/js/jquery.autocompleter.js]

newSuccess:
  stylesheets: [view]
updateSuccess:
  stylesheets: [view]
  javascripts: [contact-edit]
editSuccess:
  stylesheets: [view]
  javascripts: [contact-edit]
showSuccess:
  stylesheets: [view]
  javascripts: [contact-show]

indexSuccess:
  javascripts: [contact-filters]
filterSuccess:
  javascripts: [contact-filters]


csvSuccess:
  has_layout: off
  http_metas:
    content-type: text/comma-separated-values
    content-disposition: attachment; filename="contacts-list.csv"
