default:
  javascripts: [menu,/sfFormExtraPlugin/js/jquery.autocompleter.js]

editSuccess:
  javascripts: [contact-edit]
showSuccess:
  javascripts: [contact-show]

csvSuccess:
  has_layout: off
  http_metas:
    content-type: application/msexcel
    #content-disposition: attachment; filename="contacts.csv"
