generator:
  class: sfDoctrineGenerator
  param:
    model_class:           OrganismPhonenumber
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          organism_phonenumber
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        name:   { label: Type }
        number: { label: Phonenumber }
      list:    ~
      filter:  ~
      form:
        display: [name, number, organism_id]
      edit:    ~
      new:     ~
