# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  payment_method: VEL
  min_tickets: 9
  
  melody:
    create_user: false
    redirect_register: false
    
    name:
      key: 6qAOB371Qbio
      secret: ThisIsASecret
      callback: @evoucher
      
      provider: evoucher
      request_token_url: http://www.    # override the url - for OAuth 1 implementation only
      request_auth_url: url
      access_token_url: url
                  
      
      user:
        username:
          call: me
          path: id
          prefix: evoucher_
        first_name:
          call: me
          path: first_name
        last_name:
          call: me
          path: last_name
