generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Transaction
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          transaction
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        tickets_qty: { label: Tickets }
        delete_demands: { label: Del. }
        list_id: { label: Id }
        sf_guard_user_id: { label: User }
      list:
        display: [_list_id, _contact, _organism, closed, _tickets_qty, _delete_demands, _debt, User, updated_at]
        sort: [id,desc]
      filter:
        display: [name, contact_id, organism_id, sf_guard_user_id]
      form:    ~
      edit:    ~
      new:     ~
