generator:
  class: sfDoctrineGenerator
  param:
    model_class:           WebOrigin
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          web_origin
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        com: { label: Campaign }
        created_at: { label: Date }
        list_transaction: { label: Transaction }
        ipaddress: { label: IP address }
        sf_guard_user_id: { label: User }
        list_deal_done: { label: Done deal, type: boolean }
        list_contact: { label: Contact }
        list_transaction_amount: { label: Amount, type: number }
        recorded_filters: { help: 'Warning: embedded filters are not supported' }
      list:
        actions: []
        title: Statistics from online sales
        display: [first_page, referer, campaign, _list_transaction, transaction_id, _list_contact, _list_transaction_amount, _list_deal_done, _list_ipaddress, ipaddress, user_agent, created_at, User]
        batch_actions:
          _exceptions:
            label: Create exceptions
        object_actions: []
        sort: [created_at, desc]
        max_per_page: 100
        table_method: retrieveList
      filter:
        display:
          Externals: [referer_domain, referer, campaign, ipaddress, user_agent]
          Internals: [transaction_id, done_deal, first_page, created_at, sf_guard_user_id]
          Combinated: [recorded_filters]
      form:    ~
      edit:    ~
      new:     ~
