generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ContactRelationshipType
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          contact_relationship_type
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Types of relationships between contacts
        display: [name]
        sort: [name, '']
        object_actions:
          _edit: ~
          _delete: ~
      filter:  ~
      form:    ~
      edit:
        title: Renaming type of relationship %%name%%
      new:
        title: New type of relationship
  
