generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardUser
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_user
    with_doctrine_route:   true

    config:
      fields:
        password_again: { label: "Password (again)" }
        is_super_admin:
          label: SA
          helper: Is super admin
        is_active:      { label: Is active }
        username:       { label: Login }
        first_name:     { label: Firstname }
        last_name:      { label: Lastname }
        email_address:  { label: Email address }
        list_contact:   { label: Linked contact }
        auth_for_groups_list: { label: List of authorized groups }
        auto_groups_list: { label: Auto groups, help: "List of groups to join automatically on a contact/organism creation (careful: to be active, the user needs the permission to access this group on top of here)" }
      
      filter:
        display: [username, is_active, is_super_admin, last_name, first_name, email_address, meta_events_list, workspaces_list, prices_list]
      
      list:
        title:   User list
        display: [username, last_name, first_name, _list_contact, is_active, is_super_admin, last_login, last_name, first_name, email_address]
        object_actions: { _edit: ~, _duplicate: { name: Duplicate, action: duplicate }, _delete: ~ }

      form:
        display:
          "User":                   [username, password, password_again, first_name, last_name, email_address]
          "Permissions and groups": [is_active, is_super_admin, groups_list]
          "Public relations":       [auth_for_groups_list, auto_groups_list]
          "Ticketting items":       [meta_events_list, workspaces_list, prices_list]
          "Misc":                   [contact_id, <?php echo sfConfig::get('project_messaging_enable',false) ? '_show_jabber, ' : '' ?>member_cards_list]
        class: liGuardUserAdminForm

      edit:
        title: Editing User "%%username%%"

      new:
        title: New User
      
      show:
        title: User view
        display:
          "User":                   [username, first_name, last_name, _show_email]
          "Permissions and groups": [_show_is_active, _show_is_super_admin, _show_groups_list, _show_meta_events_list, _show_workspaces_list, _show_prices_list, _show_permissions_list]
  
