generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ManifestationEntry
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          manifestation_entry
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~
      edit:
        actions: { _save: ~ }
      new:
        actions: { _save: ~ }
