indexSuccess:
  stylesheets: [grp-event-list]
  javascripts: [lists]
editSuccess:
  stylesheets: [gauge, grp-event: { media: all }]
  javascripts: [jquery.tablescroll.js]
gaugeSuccess:
  stylesheets: [gauge, grp-event]
