all:
  credentials: [event-event]
  
edit:
  credentials: [event-event-edit]
update:
  credentials: [event-event-edit]
new:
  credentials: [event-event-new]
create:
  credentials: [event-event-new]
delete:
  credentials: [event-event-delete]
batchDelete:
  credentials: [event-event-delete]
calendar:
  credentials: [event-event-calendar]
