all:
  javascripts: [/liTinymcePlugin/tiny_mce]
  stylesheets: [manifestation]

newSuccess:
  stylesheets: [view,event]
  javascripts:  [event]
createSuccess:
  stylesheets: [view,event]
  javascripts:  [event]
updateSuccess:
  stylesheets: [view,event]
  javascripts:  [event]
editSuccess:
  stylesheets: [view,event]
  javascripts:  [event]
showSuccess:
  stylesheets: [view,event]
  javascripts:  [event]

