all:
  javascripts: [helper, tck-touchscreen?<?php echo date('Ymd') ?>, tck-touchscreen-forms?<?php echo date('Ymd') ?>, tck-touchscreen-board?<?php echo date('Ymd') ?>, vcard, event-seated-plan?<?php echo date('Ymd') ?>, /private/tck-touchscreen?<?php echo date('Ymd') ?>]
  stylesheets: [event-gauge?<?php echo date('Ymd') ?>, tck-touchscreen?<?php echo date('Ymd') ?>, event-seated-plan?<?php echo date('Ymd') ?>, /private/tck-touchscreen.css?<?php echo date('Ymd') ?>]
respawnSuccess:
  stylesheets: [-tck-touchscreen]
registeredSuccess:
  javascripts: [-*]
batchPrintSuccess:
  javascripts: [-*]

json:
  has_layout: false
  http_metas:
    content-type: application/json

closeWindowSuccess:
  layout: nude

registerSuccess:
  has_layout: false
  http_metas:
    content-type: application/json
registerError:
  has_layout: false
  http_metas:
    content-type: application/json
