generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Manifestation
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          manifestation
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        list_event: { label: Event }
        list_location: { label: Location }
        list_description: { label: Description }
      list:
        display: [_list_event, happens_at, _list_location, _list_description]
      filter:  ~
      form:
        display:
          General: [happens_at, event_id, location_id, description]
          Technical: [duration, vat, prices_list]
          Organization: [seated, online, organizers_list]
          Workspaces: [workspaces_list]
      edit:
        title: Edit Manifestation %%name%%
      new:     ~
      show:
        display:
          General: [happens_at, event_id, location_id, description]
          Technical: [duration, vat, prices_list]
          Organization: [seated, online, organizers_list]
          Workspaces: [workspaces_list]
