all:
  javascripts: [/liTinymcePlugin/tinymce.min.js, /liTinymcePlugin/jquery.tinymce.min.js]
  stylesheets: [location,manifestation]

showSuccess:
  stylesheets: [view]
editSuccess:
  stylesheets: [view]
updateSuccess:
  stylesheets: [view]
newSuccess:
  stylesheets: [view]
createSuccess:
  stylesheets: [view]
indexSuccess:
  javascripts: [list-scroll, location]
  stylesheets: [print-list: {media: print}]
