generator:
  class: sfDoctrineGenerator
  param:
    model_class:           workspace
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          workspace
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        on_ticket: { label: On ticket }
      list:
        display: [name, on_ticket, seated]
      filter:  ~
      show:
        display:
          General: [name, on_ticket, _show_seated]
          Ticketting: [_show_manifestations_list, _show_prices_list]
          Users: [_show_users_list]
      form:
        display:
          General: [name, on_ticket, seated]
          Ticketting: [prices_list, manifestations_list]
          Users: [users_list]
      edit:
        title: Edit Workspace %%name%%
      new:     ~
