generator:
  class: sfDoctrineGenerator
  param:
    model_class:           workspace
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          workspace
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [name, on_ticket]
      filter:  ~
      form:
        display:
          General: [name, on_ticket]
          Manifestations: [manifestations_list]
          Users: [users_list]
      edit:
        title: Edit Workspace %%name%%
      new:     ~
