# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [/sfAdminThemejRollerPlugin/css/jroller.css, /sfAdminThemejRollerPlugin/css/jquery/redmond/jquery-ui.custom.css, main.css, public, /private/public.css?<?php echo date('Ymd') ?>]
  javascripts:    [jquery?<?php date('Ymd') ?>,<?php // hack?? ?> public?<?php echo date('Ymd') ?>, pub-timer?<?php echo date('Ymd') ?>, helper?<?php echo date('Ymd') ?>, /private/public?<?php echo date('Ymd') ?>, jquery.nicescroll.min.js?<?php echo date('Ymd') ?>]

  has_layout:     true
  layout:         <?php echo sfConfig::get('app_options_template', 'public').PHP_EOL ?>
