edit:
  credentials: [pos-product]
update:
  credentials: [pos-product-edit]

new:
  credentials: [pos-product-new]
create:
  credentials: [pos-product-new]

delete:
  credentials: [pos-product-del]
batchDelete:
  credentials: [pos-product-del]

