<?php sfApplicationConfiguration::getActive()->loadHelpers(array('I18N')) ?>
all:
  transaction:
    display:
      intro:
        contact_id:
          class: board-alpha highlight
        professional_id:
          class: board-alpha highlight
        description:
          class: board-alpha highlight
        informations:
          class: li_table highlight
        new_transaction: ~
      content:
        content: ~
        product_infos:
          class: highlight
        board: ~
      payments:
        price_new: ~
        payment_new:
          class: highlight
        payments_list:
          class: highlight
          data_url: transaction/getPayments
    selling:
      manifestations:
        model: Manifestation
        title: <?php echo __('Manifestations').PHP_EOL ?>
        data_url: transaction/getManifestations
      #museum:
      #  model: MuseumEntry
      #  title: <?php echo __('Museum').PHP_EOL ?>
      #  fake: true
      #pointofsales:
      #  model: Product
      #  title: <?php echo __('Point of Sales').PHP_EOL ?>
      #  fake: true
