all:
  javascripts: [tck-touchscreen, tck-touchscreen-forms, tck-touchscreen-board, vcard, event-seated-plan]
  stylesheets: [tck-touchscreen, event-seated-plan]
respawnSuccess:
  stylesheets: [-tck-touchscreen]

json:
  has_layout: false
  http_metas:
    content-type: application/json
