all:
  javascripts: [tck-touchscreen, tck-touchscreen-forms, tck-touchscreen-board, vcard]
  stylesheets: [tck-touchscreen]

json:
  has_layout: false
  http_metas:
    content-type: application/json
