<?php

/**
 * Event
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Baptiste SIMON <baptiste.simon AT e-glop.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Event extends PluginEvent
{
  public function preSave($event)
  {
    $this->duration = intval($this->rawGet('duration')).'' == ''.$this->rawGet('duration')
      ? $this->rawGet('duration')
      : intval(strtotime(date('Y-m-d',0).' '.$this->rawGet('duration').'+0'));
    parent::preSave($event);
  }
  public function getDuration()
  {
    $duration = $this->rawGet('duration');
    if ( intval($this->rawGet('duration')).'' != ''.$this->rawGet('duration') )
      return $duration;
    
    $hours = floor($duration/3600);
    $minutes = floor($duration%3600/60) > 9 ? floor($duration%3600/60) : '0'.floor($duration%3600/60);
    return $hours.':'.$minutes;
  }
  
  public function getAgeMinHR()
  { return $this->getAgeHR($this->age_min); }
  public function getAgeMaxHR()
  { return $this->getAgeHR($this->age_max); }
  
  public static function getAgeHR($age)
  {
    sfContext::getInstance()->getConfiguration()->loadHelpers(array('I18N'));
    $r = format_number_choice(
      '[0]|[1]%y% year|(1,+Inf]%y% years ',
      array('%y%' => floor($age)),
      floor($age)
    );
    if ( floor($age) != $age )
    {
      if ( floor($age) == 0 )
        $r = '';
      else
        $r .= __(' and ');
      $r .= __('%m% month',array('%m%' => floor(($age - floor($age)) * 12)));
    }
    
    if ( $r ) $r .= __(' old');
    
    return $r;
  }
}
