<?php

/**
 * GaugeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GaugeTable extends PluginGaugeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object GaugeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Gauge');
    }
}