<?php

/**
 * ManifestationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ManifestationTable extends PluginManifestationTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ManifestationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Manifestation');
    }
}