<?php

/**
 * ManifestationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ManifestationTable extends PluginManifestationTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ManifestationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Manifestation');
    }

  public function createQuery($alias = 'p')
  {
    $e = $alias != 'e' ? 'e' : 'e1';
    $m = $alias != 'm' ? 'm' : 'm1';
    
    $query = parent::createQuery($alias)
        ->leftJoin("$alias.Event $e")
        ->leftJoin("$e.MetaEvent $m")
        ->orderBy("$e.name, $m.name, $alias.happens_at, $alias.duration");
    return $query;
  }
}
