<?php

/**
 * ManifestationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ManifestationTable extends PluginManifestationTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ManifestationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Manifestation');
    }

  public function createQuery($alias = 'm')
  {
    $e = $alias != 'e' ? 'e' : 'e1';
    $m = $alias != 'm' ? 'm' : 'm1';
    $l = $alias != 'l' ? 'l' : 'l1';
    $g = $alias != 'g' ? 'g' : 'g1';
    $ws = $alias != 'ws' ? 'ws' : 'ws1';
    $p = $alias != 'p' ? 'p' : 'p1';
    $c = $alias != 'c' ? 'c' : 'c1';
    $o = $alias != 'o' ? 'o' : 'o1';
    
    $query = parent::createQuery($alias)
        ->leftJoin("$alias.Event $e")
        ->leftJoin("$e.MetaEvent $m")
        ->leftJoin("$alias.Location $l")
        ->orderBy("$e.name, $m.name, $alias.happens_at, $alias.duration");
    return $query;
  }

  public function createQueryByEventId($id)
  {
    $q = $this->createQuery();
    $a = $q->getRootAlias();
    $q
      ->where('e.id = ?',$id)
      ->orderby("e.name, $a.happens_at DESC, l.name");
    return $q;
  }
}
