<?php

/**
 * ManifestationWorkspaceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ManifestationWorkspaceTable extends PluginManifestationWorkspaceTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ManifestationWorkspaceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ManifestationWorkspace');
    }
}