<?php

/**
 * WorkspaceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WorkspaceTable extends PluginWorkspaceTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WorkspaceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Workspace');
    }
}