all:
  javascripts: [/liTinymcePlugin/tiny_mce]

showSuccess:
  stylesheets: [view]
editSuccess:
  stylesheets: [view]
updateSuccess:
  stylesheets: [view]
newSuccess:
  stylesheets: [view]
createSuccess:
  stylesheets: [view]
indexSuccess:
  javascripts: [list-scroll]

