generator:
  class: sfDoctrineGenerator
  param:
    model_class:           WorkspaceUserOrdering
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          workspace_user_ordering
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Ordering your workspaces...
        display: [Workspace, rank]
        sort: [rank,asc]
        object_actions:
          _delete: ~
      filter:
        display: [workspace_id, rank]
      form:
        display: [workspace_id, rank]
      edit: ~
      new:
        title: New workspace order
