# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [/sfAdminThemejRollerPlugin/css/jroller.css, /sfAdminThemejRollerPlugin/css/jquery/redmond/jquery-ui.custom.css, main.css, public?<?php echo date('Ymd') ?>, /private/public.css?<?php echo date('Ymd') ?>]
#  stylesheets:    [main.css,public,/private/public.css]
  javascripts:    [jquery]

  has_layout:     true
  layout:         public
