generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Price
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          price
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        member_card_linked: { label: "Linked w/ MC", credentials: [tck-admin-member-cards] }
      list:
        display: [name, description, value, online, hide, member_card_linked]
        sort: ['hide, name', '']
      filter:  ~
      form:
        display:
          General: [name, description, value]
          Options: [online, hide, member_card_linked]
          Permissions: [workspaces_list, users_list]
      edit:    ~
      new:     ~
