generator:
  class: sfDoctrineGenerator
  param:
    model_class:           PricePOS
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          price_pos
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: List of associated prices
        display: [Price, updated_at]
        object_actions:
          _delete: ~
        table_method: retrieveList
        sort: [p.name, '']
      filter:  ~
      form:    ~
      edit:
        title: Edit price %%name%%
      new:     ~
