generator:
  class: sfDoctrineGenerator
  param:
    model_class:           AutoGroup
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          auto_group
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [Group]
        object_actions:
          _edit: ~
          _delete: ~
      filter:
        display: [id]
      form:    ~
      edit:    ~
      new:     ~
