generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ProductCategory
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          product_category
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [name, Vat, online, updated_at]
        sort: ['pct.name', '']
        object_actions:
          _edit: ~
          _delete: ~
        title: List of products' categories
      filter:
        display: [name, vat_id, online]
      form:
        display: [name, vat_id, online]
      edit:
        title: Edit category %%name%%
      new:     ~
