generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ProductCategory
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          product_category
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:
        display: [name, vat_id]
      form:
        display: [name, vat_id]
      edit:    ~
      new:     ~
