generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Checkpoint
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          checkpoint
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:
        display: [name, event_id, email, organism_id, legal]
      form:
        display:
          General: [event_id, name, organism_id, legal, email, description]
      edit:
        title: Edit Checkpoint "%%name%%"
      new:     ~
