newSuccess:
  stylesheets: [view]
createSuccess:
  stylesheets: [view]
updateSuccess:
  stylesheets: [view]
  javascripts: [contact-edit]
editSuccess:
  stylesheets: [view]
  javascripts: [contact-edit]
showSuccess:
  stylesheets: [view]
  javascripts: [contact-show]
