generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Contact
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          contact
    with_doctrine_route:   true
    actions_base_class:    sfActions
    extra:                 [show]

    config:
      actions: ~
      fields:
        description: { label: Keywords }
        YOBs_list:  { label: "Years of Birth (x[, x [,..]])" }
        YOB:        { label: Year of Birth }
        not_groups_list: { label: Not member of groups }
        email_list: { label: Email }
        organisms_email_list: { label: Organism's email }
        family_contact: { label: Family contact }
        phone_type: { label: Type }
        phone_number: { label: Phonenumber }
        list_phones: { label: Phonenumbers }
        member_cards_expire_at: { label: Valid on }
        control_created_at: { label: Passed in between }
        control_manifestation_id: { label: Passed on manifestations }
        control_checkpoint_id: { label: Controlled on checkpoints }
        tickets_amount_min: { label: Minimum tickets amount }
        tickets_amount_max: { label: Maximum tickets amount }
        list_emails: { label: Emails }
        list_see_orgs: { label: '' }
        organisms_list: { label: Organisms }
        list_organism: { label: Organism }
        list_professional: { label: Professional }
        list_organism_phones_list: { label: Phonenumbers }
        list_professional_emails: { label: Emails }
        list_more: { label: More }
        list_contact: { label: Contact }
        list_organism_city: { label: City }
        list_organism_postalcode: { label: Postalcode }
        list_professional_description: { label: Description }
        list_professional_id: { label: '' }
        familial_quotient_id: { credentials: [pr-social-quotient] }
        familial_situation_id: { credentials: [pr-social-situation] }
        type_of_resources_id: { credentials: [pr-social-resources] }
        email_no_newsletter: { label: No newsletter }
        email_newsletter: { label: Newsletter ? }
      list:
        display: [name, firstname, postalcode, city, _list_emails, _list_phones, _organisms_list <?php if ( sfConfig::get('app_options_design',false) ): ?>, _list_see_orgs, _list_contact, _list_professional_id, _list_organism, _list_professional, _list_organism_postalcode, _list_organism_city, _list_professional_emails, _list_organism_phones_list, _list_professional_description<?php endif ?>]
        max_per_page: <?php if ( sfConfig::get('app_options_design',false) ): ?>50<?php else: ?>20<?php endif; echo PHP_EOL; ?>
        table_method: retreiveList
        object_actions:
          <?php if ( !sfConfig::get('app_options_design',false) ): ?>_show: ~<?php endif; echo PHP_EOL; ?>
          _edit: ~
          _delete: ~
      show: 
        display:
          NONE: [_show_who, address, postalcode, city, country, _show_region, _show_email, _show_phonenumbers_list, _show_member_cards_list, _show_groups_list]
          Precisions: [_show_family_contact, npai, description, _YOBs]
          Technic: [created_at,updated_at,slug,longitude,latitude]
          Ticketting: [_show_events_list]
          Social: [_familial_situation_id, _type_of_resources_id, _familial_quotient_id]
      filter:
        display: [title, name, firstname, postalcode, city, region_id, country, email, <?php if ( sfConfig::get('app_options_design',false) && sfConfig::get(sfConfig::get('app_options_design').'_active') ): ?>email_newsletter,<?php endif ?> YOB, family_contact, <?php echo !sfConfig::get('app_options_design',false) ? 'groups_list,' : '' ?> not_groups_list, description, npai, organism_id, <?php echo !sfConfig::get('app_options_design',false) ? 'organism_category_id,' : '' ?> professional_type_id, has_email, has_address, updated_at, emails_list, event_categories_list, meta_events_list, events_list, prices_list, tickets_amount_min, tickets_amount_max, member_cards, member_cards_expire_at, control_created_at, control_manifestation_id, control_checkpoint_id]
      form: ~
      edit:
        title: Contact %%name%% %%firstname%%
        display:
          NONE:  [title, name, firstname, address, postalcode, _cities, city, country, email, <?php if ( sfConfig::get('app_options_design',false) && sfConfig::get(sfConfig::get('app_options_design').'_active') ): ?>email_no_newsletter,<?php endif ?> _show_member_cards_list, groups_list]
          Phonenumbers: [_form_phonenumbers_list]
          Precisions: [family_contact, npai, description, YOBs_list, password]
          Ticketting: [_events_list]
          Social: [familial_situation_id, type_of_resources_id, familial_quotient_id]
      new:
        title: New contact
        display:
          NONE:  [title, name, firstname, address, postalcode, _cities, city, country, email, <?php if ( sfConfig::get('app_options_design',false) && sfConfig::get(sfConfig::get('app_options_design').'_active') ): ?>email_no_newsletter,<?php endif ?>groups_list]
          Phonenumber: [phone_type, phone_number]
          Precisions: [family_contact, npai, description, YOBs_list, password]
          Social: [familial_situation_id, type_of_resources_id, familial_quotient_id]
