generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Contact
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          contact
    with_doctrine_route:   true
    actions_base_class:    sfActions
    extra:                 [show]

    config:
      actions: ~
      fields:
        description: { label: Keywords }
        YOBs_list:  { label: "Years of Birth (x[, x [,..]])" }
        YOB:        { label: Year of Birth }
        not_groups_list: { label: Not member of groups }
        email_list: { label: Email }
        organisms_email_list: { label: Organism's email }
        family_contact: { label: Family contact }
        phone_type: { label: Type }
        phone_number: { label: Phonenumber }
        list_phones: { label: Phonenumbers }
        member_cards_expire_at: { label: Valid on }
        control_created_at: { label: Passed in between }
        control_manifestation_id: { label: Passed on manifestations }
        control_checkpoint_id: { label: Controlled on checkpoints }
        tickets_amount_min: { label: Minimum tickets amount }
        tickets_amount_max: { label: Maximum tickets amount }
      list:
        display: [name, firstname, postalcode, city, email, _list_phones, _organisms_list, _organisms_email_list]
        max_per_page: 20
      show: 
        display:
          NONE: [title, _show_who, address, postalcode, city, country, _show_email, _show_phonenumbers_list, _show_member_cards_list, _show_groups_list]
          Precisions: [family_contact, npai, description, _YOBs]
          Technic: [created_at,updated_at,slug,longitude,latitude]
          Ticketting: [_show_events_list]
      filter:
        display: [title, name, firstname, postalcode, city, country, email, YOB, family_contact, groups_list, not_groups_list, description, npai, organism_id, organism_category_id, professional_type_id, has_email, has_address, updated_at, emails_list, event_categories_list, meta_events_list, events_list, prices_list, tickets_amount_min, tickets_amount_max, member_cards, member_cards_expire_at, control_created_at, control_manifestation_id, control_checkpoint_id]
      form: ~
      edit:
        title: Contact %%name%% %%firstname%%
        display:
          NONE:  [title, name, firstname, address, postalcode, _cities, city, country, email, _show_member_cards_list, groups_list]
          Phonenumbers: [_form_phonenumbers_list]
          Precisions: [family_contact, npai, description, YOBs_list, password]
          Ticketting: [_events_list]
      new:
        title: New contact
        display:
          NONE:  [title, name, firstname, address, postalcode, _cities, city, country, email, groups_list]
          Phonenumber: [phone_type, phone_number]
          Precisions: [family_contact, npai, description, YOBs_list, password]
