generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Contact
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          contact
    with_doctrine_route:   true
    actions_base_class:    sfActions
    extra:                 [show]

    config:
      actions: ~
      fields:
        description: { label: Keywords }
        YOBs_list:  { label: "Years of Birth (x[, x [,..]])" }
        YOB:        { label: Year of Birth }
        not_groups_list: { label: Not member of groups }
        email_list: { label: Email }
      list:
        display: [name, firstname, postalcode, city, _email_list, _organisms_list, _organisms_email_list]
      show: 
        display:
          NONE: [title, _show_who, address, postalcode, city, country, _show_email, _show_phonenumbers_list, _show_groups_list]
          Precisions: [npai, description, _YOBs]
          #Geolocalization: [_gmap]
          Details: [created_at,updated_at,slug,longitude,latitude]
          Ticketting: [_events_list]
      filter:
        display: [name, firstname, postalcode, city, country, YOB, family_contact, groups_list, not_groups_list, description, npai, organism_id, organism_category_id, professional_type_id, has_email, has_address, emails_list, event_categories_list, meta_events_list, events_list, prices_list]
      form: ~
      edit:
        title: Contact %%name%% %%firstname%%
        display:
          NONE:  [title, name, firstname, address, postalcode, city, country, email]
          Precisions: [npai, description, YOBs_list, family_contact, password]
          Phonenumbers: [_form_phonenumbers_list]
          Personal groups: [groups_list]
          #Geolocalization: [_gmap]
          Ticketting: [_events_list]
      new:
        title: New contact
        display:
          NONE:  [title, name, firstname, address, postalcode, city, country, email]
          Precisions: [npai, description, YOBs_list, family_contact, password]
          Groups: [groups_list]
