index:
  credentials: pr-contact
filter:
  credentials: pr-contact
searchIndexing:
  credentials: pr-contact
search:
  credentials: pr-contact
groupList:
  credentials: pr-contact
ajax:
  credentials: pr-contact
show:
  credentials: pr-contact

new:
  credentials: pr-contact-new
create:
  credentials: pr-contact-new

edit:
  credentials: pr-contact
update:
  credentials: pr-contact-edit
getSpecializedForm:
  credentials: pr-contact-edit

delete:
  credentials: pr-contact-del
batchDelete:
  credentials: pr-contact-del

labels:
  credentials: pr-contact-labels
csv:
  credentials: pr-contact-csv
group:
  credentials: pr-group-perso
