generator:
  class: sfDoctrineGenerator
  param:
    model_class:           EntryTickets
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          entry_tickets
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: []
        max_per_page: 3
      filter:
        display: []
      form:    ~
      edit:    ~
      new:     ~
