generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Hold
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          hold
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        next: { label: Discharge }
        Next: { label: Discharge }
        list_next: { label: Discharge }
        list_feeders: { label: Feeders }
        list_manifestation: { label: Manifestation }
        list_capacity: { label: Capacity, type: number }
        list_occupied: { label: Occupied, type: number }
      list:
        title: Holds list
        display: [=name, _list_manifestation, _list_capacity, _list_occupied, _list_next, _list_feeders, updated_at]
        actions:
          _new:
            credentials: [event-hold-new]
        object_actions:
          _edit:
            credentials: [event-hold-mod]
          _waitingList:
            credentials: [event-hold-transaction]
            ui-icon: arrow-1-e
            action: waitingList
            label: Waiting list
          _delete:
            credentials: [event-hold-del]
        batch_actions:
          _delete:
            credentials: [event-hold-del]
        sort: ['after, m.happens_at, ht.name', '']
      filter:
        display: [name, manifestation_id, next, feeder_id]
      form: ~
      edit:
        title: Hold "%%name%%"
        display:
          Plan: [_form_get_seats_from_transaction, _form_transaction_id, _show_seated_plan]
          General: [name, manifestation_id, next, _show_feeders, _show_capacity]
        actions:
          _list: ~
          _delete:
            credentials: [event-hold-del]
          _waiting_list:
            action: WaitingList
            ui-icon: arrow-1-e
            credentials: [event-hold-transaction]
          _save:
            credentials: [event-hold-mod]
      new:
        display:
          General: [name, manifestation_id, next]
          Plan: [_show_dummy]
          
