generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Event
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          event
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        meta_event_id: { label: Programmation }
        MetaEvent: { label: Programmation }
        name: { label: "<?php echo sfConfig::get('app_informations_events_title','') ?>" }
        list_companies: { label: Companies }
        list_picture: { label: '' }
        list_locations: { label: Location }
      list:
        batch_actions: []
        object_actions: []
        actions: []
        display: [_list_picture, _month, =name, MetaEvent, EventCategory, _dates, _list_locations, _age_min, _list_companies]
        table_method: retrievePublicList
        sort: ['min_date, m.happens_at', '']
        title: <?php echo sfConfig::get('app_informations_index','Events list').PHP_EOL ?>
        max_per_page: 100
      filter:
        display: [name, meta_event_id, event_category_id]
      form:    ~
      edit:    ~
      new:     ~
