default:
  has_layout: false
  http_metas:
    content-type: application/json
addSeatError:
  has_layout: false
  http_metas:
    content-type: application/json
removeTicketError:
  has_layout: false
  http_metas:
    content-type: application/json
autoSeatingSuccess:
  has_layout: false
  http_metas:
    content-type: application/json
addSeatSuccess:
  has_layout: false
  http_metas:
    content-type: application/json
removeTicketSuccess:
  has_layout: false
  http_metas:
    content-type: application/json
