#**********************************************************************************
#
#	    This file is part of e-venement.
# 
#    e-venement is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License.
# 
#    e-venement is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
# 
#    You should have received a copy of the GNU General Public License
#    along with e-venement; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
# 
#    Copyright (c) 2006-2011 Baptiste SIMON <baptiste.simon AT e-glop.net>
#    Copyright (c) 2006-2011 Libre Informatique [http://www.libre-informatique.fr/]
# 
#**********************************************************************************/

Workspace:
  package: event
  actAs:
    Timestampable: ~
  columns:
    name:
      type: string(255)
      notnull: true
      notblank: true
      unique: true

MetaEvent:
  package: event
  actAs: [Timestampable]
  columns:
    name:
      type:     string(255)
      notblank: true
      notnull:  true
      unique:   true
EventCategory:
  package: event
  actAs: [Timestampable]
  columns:
    name:
      type:     string(255)
      notblank: true
      notnull:  true
      unique:   true
    vat:
      type:     decimal(5)
      scale:    2
Event:
  package: event
  actAs:
    Timestampable: ~
    Sluggable:
      fields: [name]
      unique: true
  columns:
    name:
      type:         string(255)
      notblank:     true
    short_name:     string(127)
    meta_event_id:  integer
    event_category_id: integer
    event_category_description: string(255)
    description:    string
    staging:        string(255)
    staging_label:  string(255)
    writer:         string(255)
    writer_label:   string(255)
    duration:       interval
    age_min:
      type:         decimal(3)
      scale:        1
    age_max:
      type:         decimal(3)
      scale:        1
    description:    string
    extradesc:      string
    extraspec:      string
    web_price:
      type:         decimal(8)
      scale:        3
    web_price_group:
      type:         decimal(8)
      scale:        3
    image_url:      string(255)
  relations:
    EventCategory:
      foreignAlias: Events
      onDelete: RESTRICT
      onUpdate: CASCADE
    MetaEvent:
      foreignAlias: Events
      onDelete: RESTRICT
      onUpdate: CASCADE
    Companies:
      class: Organism
      refClass: EventCompany
      foreignAlias: Events
EventCompany:
  package: event
  columns:
    organism_id:
      type:     integer
      notnull:  true
      primary:  true
    event_id:
      type:     integer
      notnull:  true
      primary:  true
  relations:
    Organism:
      foreignAlias: EventCompanies
      onDelete: CASCADE
      onUpdate: CASCADE
    Event:
      foreignAlias: EventCompanies
      onDelete: CASCADE
      onUpdate: CASCADE
 
Location:
  package: event
  inheritance:
    extends: Addressable
    type: concrete
  columns:
    description:  string
    contact_id:   integer
    organism_id:  integer
    seating_plan_id: integer
    gauge_max:    integer
    gauge_min:    integer
  relations:
    SeatingPlan:
      foreignAlias: Location
      onDelete: CASCADE
      onUpdate: CASCADE
    Organism:
      foreignAlias: Locations
      onDelete: SET NULL
      onUpdate: CASCADE
    Contact:
      foreignAlias: Locations
      onDelete: SET NULL
      onUpdate: CASCADE
SeatingPlan:
  package: event
  actAs: [Timestampable]
  columns:
    image_url:    string(255)
    location_id:
      type: integer
      unique: true

Manifestation:
  package: event
  actAs:
    Timestampable: ~
  columns:
    event_id:
      type: integer
      unique: true
    location_id:
      type: integer
      unique: true
    color_id: integer
    workspace_id:
      type:         integer
      notnull:      true
  relations:
    Event:
      foreignAlias: Manifestations
      onDelete: RESTRICT
      onUpdate: CASCADE
    Location:
      foreignAlias: Manifestations
      onDelete: RESTRICT
      onUpdate: CASCADE
    Color:
      foreignAlias: Manifestations
      onDelete: SET NULL
      onUpdate: CASCADE
    Organizers:
      class: Organism
      refClass: ManifestationOrganizer
      foreignAlias: Manifestations
    Workspaces:
      class: Workspace
      refClass: ManifestationWorkspace
      foreignAlias: Manifestations
ManifestationWorkspace:
  package: event
  actAs: [Timestampable]
  columns:
    workspace_id:
      type: integer
      notnull: true
    manifestation_id:
      type: integer
      notnull: true
    gauge:
      type: integer
      notnull: true
  relations:
    Manifestations:
      foreignAlias: ManifestationWorkspaces
      onDelete: CASCADE
      onUpdate: CASCADE
    Workspaces:
      foreignAlias: ManifestationWorkspaces
      onDelete: CASCADE
      onUpdate: CASCADE
Color:
  package: event
  actAs: [Timestampable]
  columns:
    libelle:
      type:     string(255)
      notnull:  true
      notblank: true
    color:
      type:     string(255)
      notnull:  true
      notblank: true
ManifestationOrganizer:
  package: event
  columns:
    organism_id:
      type:     integer
      notnull:  true
      primary:  true
    manifestation_id:
      type:     integer
      notnull:  true
      primary:  true
  relations:
    Organism:
      foreignAlias: ManifestationOrganizers
      onDelete: CASCADE
      onUpdate: CASCADE
    Manifestation:
      foreignAlias: ManifestationOrganizers
      onDelete: CASCADE
      onUpdate: CASCADE
