#**********************************************************************************
#
#	    This file is part of e-venement.
# 
#    e-venement is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License.
# 
#    e-venement is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
# 
#    You should have received a copy of the GNU General Public License
#    along with e-venement; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
# 
#    Copyright (c) 2006-2011 Baptiste SIMON <baptiste.simon AT e-glop.net>
#    Copyright (c) 2006-2011 Libre Informatique [http://www.libre-informatique.fr/]
# 
#**********************************************************************************/

Addressable:
  package: generic
  actAs: 
    Searchable:
      fields: [name]
    Geographical: ~
    Timestampable: ~
    Sluggable:
      unique: true
      fields: [name]
  columns:
    name:
      type: string(255)
      notblank: true
    address: string
    postalcode: string(10)
    city: string(255)
    country: string(255)
    email:
      type: string(255)
      email: true
    npai:
      type: boolean
      notnull: true
      default: false

Phonenumber:
  package: generic
  actAs: [Timestampable]
  columns:
    name:
      type: string(255)
      notblank: true
    number:
      type: string(255)
      notblank: true

ModelType:
  package: generic
  actAs:
    Timestampable: ~
    Sluggable:
      fields: [type,name]
      unique: true
  columns:
    name:
      type: string(255)
    type:
      type: string(255)
      notblank: true
      notnull: true
  indexes:
    name_type:
      fields: [name, type]
      unique: true

Option:
  package: generic
  actAs:
    Timestampable:
      updated:
        disabled: true
  columns:
    type:
      type: string(255)
      notblank: true
      notnull: true
    sf_guard_user_id: integer
    name:
      type: string(255)
      notblank: true
      notnull: true
    value:
      type: string(255)
      notnull: true
  relations:
    sfGuardUser:
      foreignAlias: Options
      onDelete: CASCADE
  indexes:
    option_name_user_value_type:
      fields: [name, sf_guard_user_id, value, type]
      type: unique

Authentication:
  package: generic
  actAs:
    Timestampable:
      updated:
        disabled: true
  columns:
    sf_guard_user_id: integer
    description: string
    ip_address:  string(255)
    user_agent:  string(255)
    referer:     string(255)
    success:     boolean
  relations:
    User:
      class: sfGuardUser
      foreignAlias: Authentications
      onDelete: SET NULL
      onUpdate: CASCADE
