#**********************************************************************************
#
#	    This file is part of e-venement.
# 
#    e-venement is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License.
# 
#    e-venement is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
# 
#    You should have received a copy of the GNU General Public License
#    along with e-venement; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
# 
#    Copyright (c) 2006-2011 Baptiste SIMON <baptiste.simon AT e-glop.net>
#    Copyright (c) 2006-2011 Libre Informatique [http://www.libre-informatique.fr/]
# 
#**********************************************************************************/

Addressable:
  package: generic
  actAs: 
    Searchable:
      fields: [name]
    Geographical: ~
    Timestampable: ~
    Sluggable:
      unique: true
      fields: [name]
  columns:
    name:
      type: string(255)
      notblank: true
    address: string
    postalcode: string(10)
    city: string(255)
    country: string(255)
    email:
      type: string(255)
      email: true
    npai:
      type: boolean
      notnull: true
      default: false

Contact:
  package: rp
  inheritance:
    extends: Addressable
    type: concrete
  actAs: 
    Searchable:
      fields: [name,firstname]
    Sluggable:
      fields: [name,firstname]
  columns:
    firstname: string(255)
    title: string(23)
    description: string
    password: string(255)
Organism:
  package: rp
  inheritance:
    extends: Addressable
    type: concrete
  columns:
    url: string(255)
    description: string
    organism_category_id: integer
  relations:
    Category:
      class: OrganismCategory
      foreignAlias: Organisms

Phonenumber:
  package: generic
  actAs: [Timestampable]
  columns:
    name:
      type: string(255)
      notblank: true
    number:
      type: string(255)
      notblank: true
ContactPhonenumber:
  package: rp
  inheritance:
    extends: Phonenumber
    type: concrete
  columns:
    contact_id:
      type: integer
      notnull: true
  relations:
    Contact:
      foreignAlias: Phonenumbers
      onDelete: CASCADE
OrganismPhonenumber:
  package: rp
  inheritance:
    extends: Phonenumber
    type: concrete
  columns:
    organism_id:
      type: integer
      notnull: true
  relations:
    Organism:
      foreignAlias: Phonenumbers
      onDelete: CASCADE

OrganismCategory:
  package: rp
  actAs: 
    Timestampable: ~
    Sluggable:
      fields: [name]
  columns:
    name:
      type: string(255)
      notblank: true
YOB:
  package: rp
  actAs: [Timestampable]
  columns:
    year:
      type: integer
      notnull: true
    contact_id: integer
  relations:
    Contact:
      foreignAlias: YOBs
      onDelete: CASCADE

ProfessionalType:
  package: rp
  actAs: [Timestampable]
  columns:
    name:
      type: string(255)
      notblank: true
Professional:
  package: rp
  actAs: [Timestampable]
  columns:
    name: string(255)
    organism_id:
      type: integer
      notnull: true
    contact_id:
      type: integer
      notnull: true
    professional_type_id: integer
    contact_number: string(255)
    contact_email:
      type: string(255)
      email: true
    department: string(255)
    description: string
  relations:
    ProfessionalType:
      foreignAlias: Professionals
      onDelete: SET NULL
    Contact:
      foreignAlias: Professionals
      onDelete: CASCADE
    Organism:
      foreignAlias: Professionals
      onDelete: CASCADE

Group:
  package: group
  tableName: group_table
  actAs:
    Timestampable: ~
    Sluggable:
      fields: [name]
      unique: true
  columns:
    name:
      type: string(255)
      notblank: true
    sf_guard_user_id: integer
    description: string
  indexes:
    name_user:
      fields: [name, sf_guard_user_id]
      type: unique
  relations:
    Contacts:
      class: Contact
      refClass: GroupContact
      foreignAlias: Groups
    Professionals:
      class: Professional
      refClass: GroupProfessional
      foreignAlias: Groups
    User:
      class: sfGuardUser
      foreignAlias: Groups
      onDelete: CASCADE
GroupDetail:
  package: group
  actAs: [Timestampable]
  columns:
    group_id:
      type: integer
      notnull: true
      primary: true
    information: string
  relations:
    Group:
      foreignAlias: Members
      onDelete: CASCADE
GroupContact:
  package: group
  inheritance:
    extends: GroupDetail
    type: concrete
  columns:
    contact_id:
      type: integer
      notnull: true
      primary: true
  relations:
    Contact:
      foreignAlias: ContactGroups
      onDelete: CASCADE
GroupProfessional:
  package: group
  inheritance:
    extends: GroupDetail
    type: concrete
  columns:
    professional_id:
      type: integer
      notnull: true
      primary: true
  relations:
    Professional:
      foreignAlias: ProfessionalGroups
      onDelete: CASCADE

ModelType:
  package: generic
  actAs:
    Timestampable: ~
    Sluggable:
      fields: [type,name]
      unique: true
  columns:
    name:
      type: string(255)
    type:
      type: string(255)
      notblank: true
      notnull: true
  indexes:
    name_type:
      fields: [name, type]
      unique: true
TitleType:
  package: rp
  inheritance:
    extends: ModelType
    type: column_aggregation
    keyField: type
    keyValue: 'title'
PhoneType:
  package: rp
  inheritance:
    extends: ModelType
    type: column_aggregation
    keyField: type
    keyValue: 'phone'

Option:
  package: generic
  actAs:
    Timestampable:
      updated:
        disabled: true
  columns:
    type:
      type: string(255)
      notblank: true
      notnull: true
    sf_guard_user_id: integer
    name:
      type: string(255)
      notblank: true
      notnull: true
    value:
      type: string(255)
      notnull: true
  relations:
    sfGuardUser:
      foreignAlias: Options
      onDelete: CASCADE
  indexes:
    option_name_user_value_type:
      fields: [name, sf_guard_user_id, value, type]
      type: unique
OptionCsv:
  package: rp
  inheritance:
    extends: Option
    type: column_aggregation
    keyField: type
    keyValue: 'csv'
OptionLabels:
  package: rp
  inheritance:
    extends: Option
    type: column_aggregation
    keyField: type
    keyValue: 'labels'

Email:
  package: email
  actAs:
    Searchable:
      fields: [subject,content,from,to,cc,bcc]
    Timestampable: ~
    SoftDelete: ~
  columns:
    sf_guard_user_id: integer
    field_from:
      type:     string(255)
      email:    true
      notnull:  true
    field_to:         string
    field_cc:         string
    field_bcc:        string
    field_subject:
      type:     string
      notnull:  true
    content:
      type:     string
      notnull:  true
  relations:
    User:
      class: sfGuardUser
      foreignAlias: Emails
      onDelete: SET NULL
    Contacts:
      class: Contact
      refClass: EmailContact
      foreignAlias: Emails
    Professionals:
      class: Professional
      refClass: EmailProfessional
      foreignAlias: Emails
    Organisms:
      class: Organism
      refClass: EmailOrganism
      foreignAlias: Emails
EmailLink:
  package: email
  actAs:
    Timestampable: ~
    SoftDelete: ~
  columns:
    email_id:
      type: integer
      notnull: true
  relations:
    Email:
      foreignAlias: EmailLinks
      onDelete: CASCADE
EmailContact:
  package: email
  inheritance:
    extends: EmailLink
    type: concrete
  columns:
    contact_id:
      type: integer
      notnull: true
  relations:
    Contact:
      foreignAlias: EmailContacts
      onDelete: CASCADE
EmailOrganism:
  package: email
  inheritance:
    extends: EmailLink
    type: concrete
  columns:
    organism_id:
      type: integer
      notnull: true
  relations:
    Organism:
      foreignAlias: EmailOrganisms
      onDelete: CASCADE
EmailProfessional:
  package: email
  inheritance:
    extends: EmailLink
    type: concrete
  columns:
    professional_id:
      type: integer
      notnull: true
  relations:
    Professional:
      foreignAlias: EmailOrganisms
      onDelete: CASCADE
