#**********************************************************************************
#
#	    This file is part of e-venement.
# 
#    e-venement is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License.
# 
#    e-venement is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
# 
#    You should have received a copy of the GNU General Public License
#    along with e-venement; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
# 
#    Copyright (c) 2006-2011 Baptiste SIMON <baptiste.simon AT e-glop.net>
#    Copyright (c) 2006-2011 Libre Informatique [http://www.libre-informatique.fr/]
# 
#**********************************************************************************/

Addressable:
  actAs: 
    Geographical: ~
    Timestampable: ~
    Sluggable:
      unique: true
      fields: [name]
  columns:
    name:
      type: string(255)
      notblank: true
    address: string
    postalcode: string(10)
    city: string(255)
    country: string(255)
    email:
      type: string(255)
      email: true
    npai:
      type: boolean
      notnull: true
      default: false

Contact:
  inheritance:
    extends: Addressable
    type: concrete
  actAs: 
    Sluggable:
      fields: [name,firstname]
  columns:
    firstname: string(255)
    title: string(23)
    description: string
    password: string(255)
Organism:
  inheritance:
    extends: Addressable
    type: concrete
  columns:
    url: string(255)
    description: string
    organism_category_id: integer
  relations:
    Category:
      class: OrganismCategory
      foreignAlias: Organisms

Phonenumber:
  actAs: [Timestampable]
  columns:
    name:
      type: string(255)
      notblank: true
    number:
      type: string(255)
      notblank: true
ContactPhonenumber:
  inheritance:
    extends: Phonenumber
    type: concrete
  columns:
    contact_id:
      type: integer
      notnull: true
  relations:
    Contact:
      foreignAlias: Phonenumbers
      onDelete: CASCADE
OrganismPhonenumber:
  inheritance:
    extends: Phonenumber
    type: concrete
  columns:
    organism_id:
      type: integer
      notnull: true
  relations:
    Organism:
      foreignAlias: Phonenumbers
      onDelete: CASCADE

OrganismCategory:
  actAs: 
    Timestampable: ~
    Sluggable:
      fields: [name]
  columns:
    name:
      type: string(255)
      notblank: true
YOB:
  actAs: [Timestampable]
  columns:
    year:
      type: integer
      notnull: true
    contact_id: integer
  relations:
    Contact:
      foreignAlias: YOBs
      onDelete: CASCADE

ProfessionalType:
  actAs: [Timestampable]
  columns:
    name:
      type: string(255)
      notblank: true
Professional:
  actAs: [Timestampable]
  columns:
    name: string(255)
    organism_id:
      type: integer
      notnull: true
    contact_id:
      type: integer
      notnull: true
    professional_type_id: integer
    contact_number: string(255)
    contact_email:
      type: string(255)
      email: true
    department: string(255)
    description: string
  relations:
    ProfessionalType:
      foreignAlias: Professionals
      onDelete: SET NULL
    Contact:
      foreignAlias: Professionals
      onDelete: CASCADE
    Organism:
      foreignAlias: Professionals
      onDelete: CASCADE

Group:
  tableName: group_table
  actAs:
    Timestampable: ~
    Sluggable:
      fields: [name]
      unique: true
  columns:
    name:
      type: string(255)
      notblank: true
    sf_guard_user_id: integer
    description: string
  indexes:
    name_user:
      fields: [name, sf_guard_user_id]
      type: unique
  relations:
    Contacts:
      class: Contact
      refClass: GroupContact
      foreignAlias: Groups
    Professionals:
      class: Professional
      refClass: GroupProfessional
      foreignAlias: Groups
    User:
      class: sfGuardUser
      foreignAlias: Groups
      onDelete: CASCADE
GroupDetail:
  actAs: [Timestampable]
  columns:
    group_id:
      type: integer
      notnull: true
      primary: true
    information: string
  relations:
    Group:
      foreignAlias: Members
      onDelete: CASCADE
GroupContact:
  inheritance:
    extends: GroupDetail
    type: concrete
  columns:
    contact_id:
      type: integer
      notnull: true
      primary: true
  relations:
    Contact:
      foreignAlias: ContactGroups
      onDelete: CASCADE
GroupProfessional:
  inheritance:
    extends: GroupDetail
    type: concrete
  columns:
    professional_id:
      type: integer
      notnull: true
      primary: true
  relations:
    Professional:
      foreignAlias: ProfessionalGroups
      onDelete: CASCADE

ModelType:
  actAs:
    Timestampable: ~
    Sluggable:
      fields: [type,name]
      unique: true
  columns:
    name:
      type: string(255)
    type:
      type: string(255)
      notblank: true
      notnull: true
  indexes:
    name_type:
      fields: [name, type]
      unique: true
TitleType:
  inheritance:
    extends: ModelType
    type: column_aggregation
    keyField: type
    keyValue: 'title'
PhoneType:
  inheritance:
    extends: ModelType
    type: column_aggregation
    keyField: type
    keyValue: 'phone'
