generator:
  class: sfDoctrineGenerator
  param:
    model_class:           jabber
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          jabber
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        sf_guard_user_id: { label: User }
      list:
        display: [jabber_id, User]
        object_actions:
          _edit: ~
          _delete: ~
      filter:  ~
      form:    ~
      edit:
        title: Edit the %%User%%'s Jabber account
      new:     ~
