generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Picture
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          picture
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        list_has_content: { label: Is valid ? }
      list:
        display: [id, name, _list_has_content, type, width, height]
        sort: ['name, id', '']
      filter:
        display: [name, type, width, height]
      form:    ~
      edit:
        display:
          NONE: [name, content_file, width, height]
      new:
        display:
          NONE: [content_file, width, height]
      show:
        display:
          NONE: [name, image_tag, type, width, height]
