all:
  credentials: [event-location]

edit:
  credentials: [event-location-edit]
update:
  credentials: [event-location-edit]
new:
  credentials: [event-location-new]
create:
  credentials: [event-location-new]
delete:
  credentials: [event-location-del]
batchDelete:
  credentials: [event-location-del]
