default:
  javascripts: [menu,/sfFormExtraPlugin/js/jquery.autocompleter.js,pr]
  stylesheets: [contact,pr,main]

createSuccess:
  stylesheets: [view]
  layout: nude
newSuccess:
  stylesheets: [view]
  layout: nude
updateSuccess:
  stylesheets: [view]
  javascripts: [contact-edit]
  layout: nude
editSuccess:
  stylesheets: [view]
  javascripts: [contact-edit]
  layout: nude
showSuccess:
  stylesheets: [view]
  javascripts: [contact-show]
  layout: nude

indexSuccess:
  javascripts: [contact-list, list-scroll]
  stylesheets: [list-print: {media: print}, contact-list, batch-actions]
filterSuccess:
  javascripts: [contact-list]
  stylesheets: [list-print: {media: print}, contact-list, batch-actions]

labelsSuccess:
  has_layout: false
csvSuccess:
  has_layout: false
  http_metas:
    content-type: text/comma-separated-values
    content-disposition: attachment; filename="contacts-list.csv"

cardSuccess:
  stylesheets: [/sfAdminThemejRollerPlugin/css/reset.css: {media: all}, contact-card: {media: all}, /private/contact-card: {media: all}]
  javascripts: [-menu]
cardSuccessAndPay:
  stylesheets: [/sfAdminThemejRollerPlugin/css/reset.css: {media: all}, contact-card: {media: all}, /private/contact-card: {media: all}]
  javascripts: [-menu]

