all:
  javascripts: [/liTinymcePlugin/tinymce.min.js, /liTinymcePlugin/jquery.tinymce.min.js]
  stylesheets: [location,manifestation]

showSuccess:
  stylesheets: [view<?php if ( sfConfig::get('app_ticketting_gauge_small',true) ): ?>, event-gauge-small<?php endif ?>]
  javascripts: [<?php if ( sfConfig::get('app_ticketting_gauge_small',true) ): ?>event-gauge-small<?php endif ?>]
editSuccess:
  stylesheets: [view<?php if ( sfConfig::get('app_ticketting_gauge_small',true) ): ?>, event-gauge-small<?php endif ?>]
  javascripts: [<?php if ( sfConfig::get('app_ticketting_gauge_small',true) ): ?>event-gauge-small<?php endif ?>]
updateSuccess:
  stylesheets: [view<?php if ( sfConfig::get('app_ticketting_gauge_small',true) ): ?>, event-gauge-small<?php endif ?>]
  javascripts: [<?php if ( sfConfig::get('app_ticketting_gauge_small',true) ): ?>event-gauge-small<?php endif ?>]
newSuccess:
  stylesheets: [view]
createSuccess:
  stylesheets: [view]
indexSuccess:
  javascripts: [list-scroll, location]
  stylesheets: [print-list: {media: print}]

