# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  javascripts: [menu,organism,pr]
  stylesheets: [organism,pr,main]

newSuccess:
  stylesheets: [view]
  javascripts: [more-simple]
  layout: nude
createSuccess:
  stylesheets: [view]
  javascripts: [more-simple]
  layout: nude
updateSuccess:
  stylesheets: [view]
  javascripts: [more-simple]
  layout: nude
editSuccess:
  stylesheets: [view]
  javascripts: [more-simple]
  layout: nude
showSuccess:
  stylesheets: [view]
  javascripts: [more-simple]
  layout: nude

indexSuccess:
  javascripts: [list-scroll]
  stylesheets: [list-print: {media: print}, batch-actions]
filterSuccess:
  javascripts: [list-scroll]
  stylesheets: [list-print: {media: print}, batch-actions]

labelsSuccess:
  has_layout: false
csvSuccess:
  has_layout: false
  http_metas:
  content-type: text/comma-separated-values
  content-disposition: attachment; filename="organism-list.csv"
              
