generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Group
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          group
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        sf_guard_user_id: { label: User }
      list:
        display: [User, name, created_at]
      filter:
        display: [name, sf_guard_user_id]
      show:
        display:
          NONE: [name, User]
          Detail: [created_at, updated_at, slug]
      form:
      edit:
        title: Group %%name%%
        display:
          NONE: [name, sf_guard_user_id]
          Individuals: [contacts_list]
          Professionals: [professionals_list]
          Organisms: [organisms_list]
          #Detail: [created_at, updated_at, slug]
      new:
        title: New group
        display:
          NONE: [name, sf_guard_user_id]
          Individuals: [contacts_list]
          Professionals: [professionals_list]
          Organisms: [organisms_list]
          #Detail: [created_at, updated_at, slug]
