all:
  credentials: [admin-power]
index:
  credentials: [tck-reports]
show:
  credentials: [tck-reports]
filter:
  credentials: [tck-reports]
batch:   #batchPrintTickets:
  credentials: [tck-print-ticket]
