default:
  javascripts: [menu,/sfFormExtraPlugin/js/jquery.autocompleter.js]

updateSuccess:
  stylesheets: [view]
  javascripts: [more-simple]
newSuccess:
  stylesheets: [view]
  javascripts: [more-simple]
editSuccess:
  stylesheets: [view]
  javascripts: [more-simple]
showSuccess:
  stylesheets: [view]
  javascripts: [more-simple]

