<?php

/**
 * BaseManifestationWorkspace
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $workspace_id
 * @property integer $manifestation_id
 * @property integer $gauge
 * @property Manifestation $Manifestation
 * @property Workspace $Workspace
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Baptiste SIMON <baptiste.simon AT e-glop.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseManifestationWorkspace extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('manifestation_workspace');
        $this->hasColumn('workspace_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('manifestation_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('gauge', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Manifestation', array(
             'local' => 'manifestation_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('Workspace', array(
             'local' => 'workspace_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}