<?php

/**
 * BaseSeatingPlan
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $image_url
 * @property integer $location_id
 * @property Location $Location
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Baptiste SIMON <baptiste.simon AT e-glop.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSeatingPlan extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('seating_plan');
        $this->hasColumn('image_url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('location_id', 'integer', null, array(
             'type' => 'integer',
             'unique' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Location', array(
             'local' => 'location_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}