<?php

/**
 * BaseWorkspace
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Manifestations
 * @property Doctrine_Collection $ManifestationWorkspaces
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Baptiste SIMON <baptiste.simon AT e-glop.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWorkspace extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('workspace');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'notblank' => true,
             'unique' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Manifestation as Manifestations', array(
             'refClass' => 'ManifestationWorkspace',
             'local' => 'workspace_id',
             'foreign' => 'manifestation_id'));

        $this->hasMany('ManifestationWorkspace as ManifestationWorkspaces', array(
             'local' => 'id',
             'foreign' => 'workspace_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}