indexSuccess:
  stylesheets: [grp-event-list]
  javascripts: [lists]
editSuccess:
  stylesheets: [gauge, grp-event: { media: all }]
gaugeSuccess:
  stylesheets: [gauge, grp-event]

csvSuccess:
  has_layout: false
  http_metas:
    content-type: text/comma-separated-values
    content-disposition: attachment; filename="accepted.csv"
              
