generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Email
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          email
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        field_from:     { label: From: }
        field_subject:  { label: Subject: }
        field_to:       { label: To: }
        field_cc:       { label: Cc: }
        field_bcc:      { label: Bcc: }
        content:        { label: Content: }
        test_address:   { label: Test email address: }
        updated_at:     { label: Last access }
      list:
        display: [User,field_subject,sent,created_at,updated_at]
      filter:  ~
      form:    ~
      edit:
        display:
          1. Content:   [field_from, field_subject, content]
          2. Recievers: [contacts_list, professionals_list, organisms_list, field_to, field_cc, field_bcc]
          3. Validate:  [test_address, _test_button]
          4. Send:      [_send_button]
      new:
        display:
          1. Content:   [field_from, field_subject, content]
          2. Recievers: [contacts_list, professionals_list, organisms_list, field_to, field_cc, field_bcc]
          3. Validate:  [test_address, _test_button]
          4. Send (test first!):      [_send_empty]
