generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardPermission
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_permission
    with_doctrine_route:   true

    config:
      list:
        title: Permission list
        display: [=name, description, created_at, updated_at]
        sort: [name, '']
        object_actions:
          _edit: ~
          _delete: ~
        max_per_page: 50
      
      edit:
        title: Editing Permission "%%name%%"

      new:
        title: New Permission

      form:
        display: [name, description, groups_list, users_list]
      
      show:
        title: Viewing permission
        display:
          Permission: [name, description]
          Users and groups: [_show_groups_list, _show_users_list]
