indexSuccess:
  javascripts: [list-scroll]
editSuccess:
  stylesheets: [stats]

extractSuccess:
  layout: false
  http_metas:
    content-type: application/xml
extractContentSuccess:
  layout: false
  http_metas:
    content-type: text/csv
    content-disposition: 'attachment; filename="survey.csv"'
