generator:
  class: sfDoctrineGenerator
  param:
    model_class:           invoice
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          invoice
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        sf_guard_user_id: { label: User }
      list:
        display: [_id,_transaction_id,_contact,_manifestations,created_at,User]
        sort: [id,desc]
        table_method: retrieveList
      filter:
        display: [_filter_id,transaction_id,created_at,sf_guard_user_id, tickets_value]
      form:    ~
      edit:    ~
      new:     ~
