generator:
  class: sfDoctrineGenerator
  param:
    model_class:           SurveyAnswer
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          survey_answer
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [_list_survey, _list_contact, Query, lang, value, updated_at]
        actions:        []
        object_actions: []
        batch_actions:  []
      filter:
        display: [survey_id, contact_id, survey_query_id, lang, value, updated_at]
      form:    ~
      edit:    ~
      new:     ~
