index:
  credentials: pr-contact
filter:
  credentials: pr-contact
ajax:
  credentials: pr-contact
show:
  credentials: pr-contact

new:
  credentials: pr-contact-edit
create:
  credentials: pr-contact-edit

edit:
  credentials: pr-contact-edit
update:
  credentials: pr-contact-edit

delete:
  credentials: pr-contact-edit
batchDelete:
  credentials: pr-contact-edit
