generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Control
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          control
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        list_transaction_id: { label: Transaction, type: number }
        list_ticket_id: { type: number }
        list_state: { label: State }
        list_contacts: { label: Contact }
        list_professional: { label: Professional }
        list_groups: { label: Groups }
        list_value: { label: Value, type: number }
        list_price: { label: Price }
        list_seat: { label: Seat }
        sf_guard_user_id: { label: User }
        list_manifestation: { label: Manifestation }
        list_created_at: { type: date }
      list:
        title: Controls overview
        display: [checkpoint_id, Checkpoint, _list_manifestation, id, _list_type, _list_seat, _list_price, _list_value, _list_state, created_at, _list_created_at, _list_contacts, _list_professional, _list_groups, comment, _list_transaction_id, ticket_id, _list_ticket_id, User]
        sort: [created_at, desc]
        object_actions: []
        batch_actions: []
        actions: []
        max_per_page: 50
      filter:
        display: [manifestation_id, checkpoint_id, sf_guard_user_id, created_at]
      form:    ~
      edit:    ~
      new:     ~
