cash:
  credentials: [tck-ledger-cash]

sales:
  credentials: [tck-ledger-sales]

both:
  credentials: [tck-ledger-sales, tck-ledger-cash]

extract:
  credentials: [tck-ledger-sales, tck-ledger-cash]
