<?php

/**
 * ContactTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContactTable extends AddressableTable
{
  /*
  public function retrieveInformationsForListing(Doctrine_Query $q)
  {
    $rootAlias = $q->getRootAlias();
    $q->leftJoin("$rootAlias.Professionals p")
      ->leftJoin('p.Organism o')
      ->orderBy("$rootAlias.name, $rootAlias.firstname, $rootAlias.city");
    return $q;
  }
  */
  
  public function createQuery($alias = 'a')
  {
    $p  = 'p'  != $alias ? 'p'  : 'p1';
    $o  = 'o'  != $alias ? 'o'  : 'o1';
    $g  = 'g'  != $alias ? 'g'  : 'g1';
    $u  = 'u'  != $alias ? 'u'  : 'u1';
    $pn = 'pn' != $alias ? 'pn' : 'pn1';
    $y  = 'y'  != $alias ? 'y' : 'y1';
    
    $query = parent::createQuery($alias)
      ->leftJoin("$alias.Professionals $p")
      ->leftJoin("$p.Organism $o")
      ->leftJoin("$alias.Groups $g")
      ->leftJoin("$g.User $u")
      ->leftJoin("$alias.Phonenumbers $pn")
      ->leftJoin("$alias.YOBs $y");
    return $query;
  }
  
    /*
     * Returns an instance of this class.
     *
     * @return object ContactTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Contact');
    }
}
