<?php

/**
 * Contact
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Contact extends BaseContact
{
  public function __toString()
  {
    return $this->firstname.' '.$this->name;
  }
  
  public function getYOBsString()
  {
    $arr = array();
    foreach ( $this->YOBs as $YOB )
      $arr[] = (string)$YOB;
    sort($arr);
    return implode(', ',$arr);
  }
}
