<?php

/**
 * GroupProfessionalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GroupProfessionalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GroupProfessionalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GroupProfessional');
    }
}