<?php

/**
 * OptionCsvTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OptionCsvTable extends OptionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object OptionCsvTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OptionCsv');
    }
}