<?php

/**
 * OrganismPhonenumberTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrganismPhonenumberTable extends PhonenumberTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrganismPhonenumberTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OrganismPhonenumber');
    }
}