<?php

/**
 * PhonenumberTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PhonenumberTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PhonenumberTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Phonenumber');
    }
}