<?php

/**
 * ProfessionalTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfessionalTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfessionalTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProfessionalType');
    }
}