generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Survey
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          survey
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [name, _list_nb_queries]
        object_actions:
          _show: ~
          _edit: ~
          _delete: ~
      filter:  ~
      form:
        display:
          Général: [name, description, _show_queries]
          Answers: [_show_answers]
          Used by: [ApplyTo]
        actions:
          _list: ~
          _delete: ~
          _show: ~
          _add_query:
            action: addQuery
            ui-icon: plus
          _save: ~
      edit:    ~
      new:     ~
