update:
  credentials: [srv-survey-edit]

new:
  credentials: [srv-survey-new]
create:
  credentials: [srv-survey-new]

delete:
  credentials: [srv-survey-del]
batchDelete:
  credentials: [srv-survey-del]
