generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Professional
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          professional
    with_doctrine_route:   true
    actions_base_class:    sfActions
    extra:                 [show]

    config:
      actions: ~
      fields:
        name: { label: Function }
        ProfessionalType: { label: Type of function }
        professional_type_id: { label: Type of function }
        contact_email: { label: Email address }
        contact_number: { label: Phone number }
      list:    ~
      show:
        display: [Organism, department, name, ProfessionalType, contact_email, contact_number, description, _show_groups_list]
      filter:  ~
      form:
        display:
          NONE: [contact_id, organism_id, professional_type_id, name, department, contact_number, contact_email, description, groups_list]
      edit:    ~
      new:     ~
