generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ProductCategory
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          product
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        list_children: { label: Subcategories }
        list_name: { label: Category }
      list:
        display: [_list_name, _list_children]
        batch_actions: []
        object_actions: []
        actions: []
        sort: [pct.name, childrent.name]
        table_method: retrievePublicList
        max_per_page: 100
        title: <?php echo sfConfig::get('app_informations_store','Products list').PHP_EOL ?>
      filter:
        display: [name, product_category_id]
      form:    ~
      edit:    ~
      new:     ~
