generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Authentication
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          authentication
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [User, description, ip_address, user_agent, referer, success, created_at]
        object_actions: []
        batch_actions: []
        actions: []
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
