generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Manifestation
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          manifestation
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        happens_at: { label: Date }
      list:
        object_actions: []
        actions: []
        batch_actions: []
        sort: ['happens_at, rank', '']
        display: [=happens_at, Event, Location, _MetaEvent]
        title: Dates list
        table_method: retrievePublicList
      filter:
        display: [event_id, happens_at]
      form:    ~
      edit:    ~
      new:     ~
