indexSuccess:
  javascripts: [helper]
default:
  javascripts: [jquery, event-seated-plan?<?php echo date('Ymd') ?>]
  stylesheets: [event-seated-plan?<?php echo date('Ymd') ?>]
showSuccess:
  stylesheets: [pub-manifestation?<?php echo date('Ymd') ?>]
  javascripts: [public?<?php echo date('Ymd') ?>]
