indexSuccess:
  stylesheets: [grp-event-list]
  javascripts: [lists, list-scroll]
editSuccess:
  stylesheets: [gauge, grp-event: { media: all }]
  javascripts: [grp-event, <?php if ( !sfConfig::get('app_options_remove_slow_js',false) ): ?>jquery.tablescroll.js<?php endif ?>]
gaugeSuccess:
  stylesheets: [gauge, grp-event]

acceptedSuccess:
  has_layout: false
  http_metas:
    content-type: text/comma-separated-values
    content-disposition: attachment; filename="accepted.csv"
refusedSuccess:
  has_layout: false
  http_metas:
    content-type: text/comma-separated-values
    content-disposition: attachment; filename="refused.csv"
