generator:
  class: sfDoctrineGenerator
  param:
    model_class:           SlavePing
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          slave_ping
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        sort: [id, desc]
      filter:
        display: [state, created_at]
      form:    ~
      edit:    ~
      new:     ~
