generator:
  class: sfDoctrineGenerator
  param:
    model_class:           PriceManifestation
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          price_manifestation
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [Manifestation, Price, value]
      filter:  ~
      form:    ~
      edit:
        display: [_show_manifestation, _show_price, value]
      new:
        display: [manifestation_id, price_id, value]
