generator:
  class: sfDoctrineGenerator
  param:
    model_class:           HoldTransaction
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          hold_transaction
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        list_contact: { label: Contact }
        list_professional: { label: Function }
        list_nb: { label: Quantity, type: number }
        list_nb_seated: { label: Seated, type: number }
        list_nb_printed: { label: Printed, type: number }
        list_transaction_id: { label: Transaction }
        pretickets: { label: Transitionals, type: number }
      list:
        title: Waiting list for hold:
        display: [Hold, _list_transaction_id, _list_contact, _list_professional, pretickets, _list_nb_seated, _list_nb_printed, _list_nb, rank]
        actions:
          _new: ~
          _back:
            action: back
            ui-icon: arrowreturnthick-1-w
          _seat:
            action: seat
            ui-icon: signal-diag
          _dump:
            action: dump
            ui-icon: arrow-4-diag
        batch_actions:
          _delete:
            credentials: [event-hold-transaction-del]
        object_actions:
          _minus:
            action: minus
            label: Less tickets
            ui-icon: minus
          _plus:
            action: plus
            label: More tickets
            ui-icon: plus
          _edit:
            credentials: [tck-transaction]
          _delete:
            credentials: [event-hold-transaction-del]
        sort: ['rank', '']
        max_per_page: 50
      filter:
        display: [transaction_id]
      form:    ~
      edit:
        title: 'Edit held transaction #%%transaction_id%%'
        display: [_show_transaction, _show_nb, _show_nb_printed, _show_nb_seated]
      new:
        display: [hold_id]
        actions:
          _list: ~
          _save: ~
