all:
  credentials: [admin-power]

index:
  credentials: [event-hold-transaction] #142
new:
  credentials: [event-hold-transaction-new] #138
create:
  credentials: [event-hold-transaction-new] #138
delete:
  credentials: [event-hold-transaction-delete] #139
batchDelete:
  credentials: [event-hold-transaction-delete] #139

dump:
  credentials: [event-hold-transaction-new] #138
seat:
  credentials: [event-hold-transaction-convert] #141
plus:
  credentials: [event-hold-transaction-mod] #143
minus:
  credentials: [event-hold-transaction-mod] #143

changeRank:
  credentials: [event-hold-transaction-order] #140

back:
  credentials: [event-hold]
