generator:
  class: sfDoctrineGenerator
  param:
    model_class:           FamilialSituation
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          familial_situation
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [name]
        object_actions:
          _edit: ~
          _delete: ~
        title: List of familial situations
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
