generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Manifestation
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          manifestation
    with_doctrine_route:   true
    actions_base_class:    sfActions

<?php $vel = sfConfig::get('app_tickets_vel', array()); echo PHP_EOL; ?>

    config:
      actions: ~
      fields:
        happens_at: { label: Date }
        formatted_date: { label: Date }
        happens_at_time_h_r: { label: Time }
        list_tickets: { label: Tickets }
        list_picture: { label: '' }
      list:
        object_actions: []
        actions: []
        batch_actions: []
        sort: ['happens_at, wuo.rank', '']
        display: [_list_picture, _list_happens_at, _list_day_name, =formatted_date, happens_at_time_h_r, Event, Location, _MetaEvent<?php if ( isset($vel['display_tickets_in_manifestations_list']) && $vel['display_tickets_in_manifestations_list'] ): ?>, _list_tickets<?php endif ?>]
        title: Dates list
        table_method: retrievePublicList
        max_per_page: 100
      filter:
        display: [event_id, happens_at]
      form:    ~
      edit:    ~
      new:     ~
