default:
  javascripts: [jquery, event-seated-plan?<?php echo date('Ymd') ?>]
  stylesheets: [event-seated-plan?<?php echo date('Ymd') ?>]
indexSuccess:
  javascripts: [public?<?php echo date('Ymd') ?>, helper]
showSuccess:
  stylesheets: [pub-manifestation?<?php echo date('Ymd') ?>]
  javascripts: [public?<?php echo date('Ymd') ?>, helper-cookies]
icalSuccess:
  has_layout: false
  http_metas:
    content-type: text/calendar
        
