index:
  credentials: pr-organism
filter:
  credentials: pr-organism
searchIndexing:
  credentials: pr-organism
search:
  credentials: pr-organism
groupList:
  credentials: pr-organism
ajax:
  credentials: pr-organism
show:
  credentials: pr-organism

new:
  credentials: pr-organism-new
create:
  credentials: pr-organism-new

edit:
  credentials: pr-organism
update:
  credentials: pr-organism-edit

delete:
  credentials: pr-organism-del
batchDelete:
  credentials: pr-organism-del

csv:
  credentials: [ pr-contact-csv, pr-organism ]
vcf:
  credentials: [ pr-contact-csv, pr-organism ]
labels:
  credentials: [ pr-contact-labels, pr-organism ]
group:
  credentials: pr-group-perso
