generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Event
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          event
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        EventCategory: { label: Category }
        event_category_id: { label: Category }
        event_category_description: { label: Detailed category }
        duration: { label: Duration }
        companies_list: { label: Compagnies }
        extradesc: { label: Extra description }
        extraspec: { label: Extra specification }
        image_url: { label: Image URL }
        age_min_h_r: { label: Age min }
        age_max_h_r: { label: Age max }
        duration_h_r: { label: Duration }
        short_name: { label: Short name }
        staging_label: { label: Staging label }
        writer_label: { label: Writer label }
      list:
        title: Event List
        display: [MetaEvent, name, EventCategory, event_category_description, duration, age_min_h_r, age_max_h_r]
      filter:
        display: [meta_event_id, event_category_id, name, staging, writer, duration, age_min, age_max, companies_list]
      form:
        display:
          General:   [name, short_name, event_category_description, event_category_id, meta_event_id]
          Technical: [companies_list, duration, age_min, age_max]
          Details:   [staging_label, staging, writer_label, writer, description]
          Web Content: [web_price, web_price_group, image_url, extradesc, extraspec]
          Checkpoints: [_form_checkpoints]
      edit:
        title: Edit Event %%name%%
      new:
      show:
        display:
          General:   [name, short_name, event_category_description, _show_event_category, _show_meta_event]
          Technical: [_show_companies_list, duration, age_min_h_r, age_max_h_r]
          Details:   [staging_label, staging, writer_label, writer, _show_description]
          Web Content: [_show_extradesc, _show_extraspec, web_price, web_price_group, _show_image_url]
