all:
  javascripts: [/liTinymcePlugin/tiny_mce]
  stylesheets: [manifestation]

indexSuccess:
  stylesheets: [event-list, list-print: {media: print}]
  javascripts: [list-scroll]
newSuccess:
  stylesheets: [view,event,/private/event.css]
  javascripts:  [event]
createSuccess:
  stylesheets: [view,event,/private/event.css]
  javascripts:  [event]
updateSuccess:
  stylesheets: [view,event,checkpoint,/private/event.css]
  javascripts:  [event,checkpoint]
editSuccess:
  stylesheets: [view,event,checkpoint,/private/event.css]
  javascripts:  [event,checkpoint]
showSuccess:
  stylesheets: [view,event,/private/event.css]
  javascripts:  [event]

