all:
  credentials: [tck-control-overview]

edit:
  credentials: [tck-control-admin]
update:
  credentials: [tck-control-admin]
new:
  credentials: [tck-control-admin]
create:
  credentials: [tck-control-admin]
delete:
  credentials: [tck-control-admin]
batchDelete:
  credentials: [tck-control-admin]
