generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Manifestation
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          manifestation
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        list_event: { label: Event }
        list_location: { label: Location }
        list_description: { label: Memo }
        happens_at: { label: Date }
        ends_at: { type: Date }
        id: { label: ID Manif }
        online_limit: { label: Online limit }
        description: { label: Memo }
        no_print: { label: Preprinted ticketting }
        reservation_optional: { label: This is an option, type: Boolean }
        blocking: { label: Blocking, type: Boolean }
        reservation_ends_at: { label: Ends at, type: Date }
        reservation_begins_at: { label: Begins at, type: Date }
        reservation_confirmed: { label: Confirmed, credentials: event-reservation-confirm }
        reservation_description: { label: Comment }
        contact_id: { label: Applicant, credentials: event-reservation-change-contact }
        booking_list: { label: Extra locations }
        ExtraInformations: { label: Extra informations }
      list:
        display: [_list_event, happens_at, _list_location, _list_description]
        object_actions:
          _edit:
            credentials: event-manif-edit
          _periodicity:
            action: periodicity
            credentials: event-manif-edit
          #_delete:
          #  credentials: event-manif-edit
      filter:
        display: []
      form: ~
      edit:
        title: Edit Manifestation %%name%%
        display:
          General:      [happens_at, ends_at, _id, event_id, location_id, _show_gauge_txt, color_id, _form_prices]
          Ticketting:   [duration, vat_id, online_limit, depends_on, _show_is_necessary_to, organizers_list, no_print]
          Workspaces:   [_form_workspaces, _show_workspaces_list]
          <?php $config = sfConfig::get('app_manifestation_reservations',array('enable' => false)); if ( isset($configs['enable']) && $config['enable'] ): echo PHP_EOL; ?>
          Resources:  [booking_list, _form_applicant_id, contact_id, reservation_begins_at, reservation_ends_at, blocking, reservation_confirmed, reservation_optional, reservation_description]
          <?php endif; echo PHP_EOL; ?>
          Extra informations:  [description<?php if ( sfConfig::get('app_manifestation_extra_informations_enable',true) ): ?>, ExtraInformations<?php endif ?>]
          #Tickets:      [_show_tickets_list]
          #Spectators:   [_show_spectators_list]
          #Unbalanced:   [_show_unbalanced_list]
      new:
        display:
          General: [happens_at, ends_at, event_id, location_id, color_id]
          Ticketting: [duration, vat_id, online_limit, depends_on, organizers_list, no_print]
          <?php $config = sfConfig::get('app_manifestation_reservations',array('enable' => false)); if ( isset($configs['enable']) && $config['enable'] ): echo PHP_EOL; ?>
          Resources:  [booking_list, _form_applicant_id, contact_id, reservation_begins_at, reservation_ends_at, blocking, reservation_confirmed, reservation_optional, reservation_description]
          <?php endif; echo PHP_EOL; ?>
          Extra informations:  [description]
        actions: { _save: ~, _list: ~ }
      show:
        display:
          General:    [_show_event, id, _show_happens_at, _show_ends_at, _show_location, _show_gauge_txt, _show_color, _show_prices_list]
          Ticketting: [_show_duration, _show_vat, _show_online_limit, _show_depends_on, _show_is_necessary_to, _show_organizers_list, _show_no_print]
          Workspaces: [_show_workspaces_list]
          Tickets:    [_show_tickets_list_empty]
          Spectators: [_show_spectators_list_empty]
          Unbalanced: [_show_unbalanced_list]
          <?php $config = sfConfig::get('app_manifestation_reservations',array('enable' => false)); if ( isset($configs['enable']) && $config['enable'] ): echo PHP_EOL; ?>
          Resources:  [_show_booking_list, _show_applicant_id, _show_reservation_begins_at, _show_reservation_ends_at, _show_blocking, _show_confirmed, _show_optional, _show_reservation_description]
          <?php endif; echo PHP_EOL; ?>
          Extra informations: [_show_description]
