all:
  stylesheets: [manifestation]
  javascripts: [manifestation]

showSuccess:
  stylesheets: [manifestation-view,view]
editSuccess:
  stylesheets: [manifestation-view,view]
newSuccess:
  stylesheets: [manifestation-view,view]
updateSuccess:
  stylesheets: [manifestation-view,view]
createSuccess:
  stylesheets: [manifestation-view,view]

templatingSuccess:
  stylesheets: [/sfFormExtraPlugin/css/jquery.autocompleter.css,/cxFormExtraPlugin/css/cx_open_list.css]
  javascripts: [/sfFormExtraPlugin/js/jquery.autocompleter.js,/cxFormExtraPlugin/js/cx_open_list.js]
