<?php

/**
 * BaseOrganismCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Organisms
 * 
 * @method string              getName()      Returns the current record's "name" value
 * @method Doctrine_Collection getOrganisms() Returns the current record's "Organisms" collection
 * @method OrganismCategory    setName()      Sets the current record's "name" value
 * @method OrganismCategory    setOrganisms() Sets the current record's "Organisms" collection
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOrganismCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('organism_category');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notblank' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Organism as Organisms', array(
             'local' => 'id',
             'foreign' => 'organism_category_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}