<?php

/**
 * BaseGroupProfessional
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $professional_id
 * @property Professional $Professional
 * 
 * @method integer           getProfessionalId()  Returns the current record's "professional_id" value
 * @method Professional      getProfessional()    Returns the current record's "Professional" value
 * @method GroupProfessional setProfessionalId()  Sets the current record's "professional_id" value
 * @method GroupProfessional setProfessional()    Sets the current record's "Professional" value
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGroupProfessional extends GroupDetail
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('group_professional');
        $this->hasColumn('professional_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Professional', array(
             'local' => 'professional_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}