<?php

/**
 * BaseYOB
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $year
 * @property integer $contact_id
 * @property Contact $Contact
 * 
 * @method integer getYear()       Returns the current record's "year" value
 * @method integer getContactId()  Returns the current record's "contact_id" value
 * @method Contact getContact()    Returns the current record's "Contact" value
 * @method YOB     setYear()       Sets the current record's "year" value
 * @method YOB     setContactId()  Sets the current record's "contact_id" value
 * @method YOB     setContact()    Sets the current record's "Contact" value
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseYOB extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('y_o_b');
        $this->hasColumn('year', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('contact_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Contact', array(
             'local' => 'contact_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}