<?php

/**
 * BaseOrganism
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $url
 * @property string $description
 * @property integer $organism_category_id
 * @property OrganismCategory $Category
 * @property Doctrine_Collection $Phonenumbers
 * @property Doctrine_Collection $Professionals
 * 
 * @method string              getUrl()                  Returns the current record's "url" value
 * @method string              getDescription()          Returns the current record's "description" value
 * @method integer             getOrganismCategoryId()   Returns the current record's "organism_category_id" value
 * @method OrganismCategory    getCategory()             Returns the current record's "Category" value
 * @method Doctrine_Collection getPhonenumbers()         Returns the current record's "Phonenumbers" collection
 * @method Doctrine_Collection getProfessionals()        Returns the current record's "Professionals" collection
 * @method Organism            setUrl()                  Sets the current record's "url" value
 * @method Organism            setDescription()          Sets the current record's "description" value
 * @method Organism            setOrganismCategoryId()   Sets the current record's "organism_category_id" value
 * @method Organism            setCategory()             Sets the current record's "Category" value
 * @method Organism            setPhonenumbers()         Sets the current record's "Phonenumbers" collection
 * @method Organism            setProfessionals()        Sets the current record's "Professionals" collection
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOrganism extends Addressable
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('organism');
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('organism_category_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('OrganismCategory as Category', array(
             'local' => 'organism_category_id',
             'foreign' => 'id'));

        $this->hasMany('OrganismPhonenumber as Phonenumbers', array(
             'local' => 'id',
             'foreign' => 'organism_id'));

        $this->hasMany('Professional as Professionals', array(
             'local' => 'id',
             'foreign' => 'organism_id'));
    }
}