<?php

/**
 * BaseOrganismPhonenumber
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $organism_id
 * @property Organism $Organism
 * 
 * @method integer             getOrganismId()  Returns the current record's "organism_id" value
 * @method Organism            getOrganism()    Returns the current record's "Organism" value
 * @method OrganismPhonenumber setOrganismId()  Sets the current record's "organism_id" value
 * @method OrganismPhonenumber setOrganism()    Sets the current record's "Organism" value
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOrganismPhonenumber extends Phonenumber
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('organism_phonenumber');
        $this->hasColumn('organism_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Organism', array(
             'local' => 'organism_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}