<?php

/**
 * BaseContact
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $firstname
 * @property string $title
 * @property string $description
 * @property string $password
 * @property Doctrine_Collection $Phonenumbers
 * @property Doctrine_Collection $YOBs
 * @property Doctrine_Collection $Professionals
 * @property Doctrine_Collection $Groups
 * @property Doctrine_Collection $GroupContacts
 * 
 * @method string              getFirstname()     Returns the current record's "firstname" value
 * @method string              getTitle()         Returns the current record's "title" value
 * @method string              getDescription()   Returns the current record's "description" value
 * @method string              getPassword()      Returns the current record's "password" value
 * @method Doctrine_Collection getPhonenumbers()  Returns the current record's "Phonenumbers" collection
 * @method Doctrine_Collection getYOBs()          Returns the current record's "YOBs" collection
 * @method Doctrine_Collection getProfessionals() Returns the current record's "Professionals" collection
 * @method Doctrine_Collection getGroups()        Returns the current record's "Groups" collection
 * @method Doctrine_Collection getGroupContacts() Returns the current record's "GroupContacts" collection
 * @method Contact             setFirstname()     Sets the current record's "firstname" value
 * @method Contact             setTitle()         Sets the current record's "title" value
 * @method Contact             setDescription()   Sets the current record's "description" value
 * @method Contact             setPassword()      Sets the current record's "password" value
 * @method Contact             setPhonenumbers()  Sets the current record's "Phonenumbers" collection
 * @method Contact             setYOBs()          Sets the current record's "YOBs" collection
 * @method Contact             setProfessionals() Sets the current record's "Professionals" collection
 * @method Contact             setGroups()        Sets the current record's "Groups" collection
 * @method Contact             setGroupContacts() Sets the current record's "GroupContacts" collection
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContact extends Addressable
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('contact');
        $this->hasColumn('firstname', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('title', 'string', 23, array(
             'type' => 'string',
             'length' => 23,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('password', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ContactPhonenumber as Phonenumbers', array(
             'local' => 'id',
             'foreign' => 'contact_id'));

        $this->hasMany('YOB as YOBs', array(
             'local' => 'id',
             'foreign' => 'contact_id'));

        $this->hasMany('Professional as Professionals', array(
             'local' => 'id',
             'foreign' => 'contact_id'));

        $this->hasMany('Group as Groups', array(
             'refClass' => 'GroupContact',
             'local' => 'contact_id',
             'foreign' => 'group_id'));

        $this->hasMany('GroupContact as GroupContacts', array(
             'local' => 'id',
             'foreign' => 'contact_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
              1 => 'firstname',
             ),
             ));
        $this->actAs($sluggable0);
    }
}