<?php

/**
 * BaseGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $sf_guard_user_id
 * @property string $description
 * @property Doctrine_Collection $Contacts
 * @property Doctrine_Collection $Professionals
 * @property sfGuardUser $User
 * @property Doctrine_Collection $GroupContacts
 * 
 * @method string              getName()             Returns the current record's "name" value
 * @method integer             getSfGuardUserId()    Returns the current record's "sf_guard_user_id" value
 * @method string              getDescription()      Returns the current record's "description" value
 * @method Doctrine_Collection getContacts()         Returns the current record's "Contacts" collection
 * @method Doctrine_Collection getProfessionals()    Returns the current record's "Professionals" collection
 * @method sfGuardUser         getUser()             Returns the current record's "User" value
 * @method Doctrine_Collection getGroupContacts()    Returns the current record's "GroupContacts" collection
 * @method Group               setName()             Sets the current record's "name" value
 * @method Group               setSfGuardUserId()    Sets the current record's "sf_guard_user_id" value
 * @method Group               setDescription()      Sets the current record's "description" value
 * @method Group               setContacts()         Sets the current record's "Contacts" collection
 * @method Group               setProfessionals()    Sets the current record's "Professionals" collection
 * @method Group               setUser()             Sets the current record's "User" value
 * @method Group               setGroupContacts()    Sets the current record's "GroupContacts" collection
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('group_table');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notblank' => true,
             'length' => 255,
             ));
        $this->hasColumn('sf_guard_user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             ));


        $this->index('name_user', array(
             'fields' => 
             array(
              0 => 'name',
              1 => 'sf_guard_user_id',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Contact as Contacts', array(
             'refClass' => 'GroupContact',
             'local' => 'group_id',
             'foreign' => 'contact_id'));

        $this->hasMany('Professional as Professionals', array(
             'refClass' => 'GroupProfessional',
             'local' => 'group_id',
             'foreign' => 'professional_id'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'sf_guard_user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('GroupDetail as GroupContacts', array(
             'local' => 'id',
             'foreign' => 'group_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             'unique' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}