<?php

/**
 * BaseAddressable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $address
 * @property string $postalcode
 * @property string $city
 * @property string $country
 * @property string $email
 * @property boolean $npai
 * 
 * @method string      getName()       Returns the current record's "name" value
 * @method string      getAddress()    Returns the current record's "address" value
 * @method string      getPostalcode() Returns the current record's "postalcode" value
 * @method string      getCity()       Returns the current record's "city" value
 * @method string      getCountry()    Returns the current record's "country" value
 * @method string      getEmail()      Returns the current record's "email" value
 * @method boolean     getNpai()       Returns the current record's "npai" value
 * @method Addressable setName()       Sets the current record's "name" value
 * @method Addressable setAddress()    Sets the current record's "address" value
 * @method Addressable setPostalcode() Sets the current record's "postalcode" value
 * @method Addressable setCity()       Sets the current record's "city" value
 * @method Addressable setCountry()    Sets the current record's "country" value
 * @method Addressable setEmail()      Sets the current record's "email" value
 * @method Addressable setNpai()       Sets the current record's "npai" value
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAddressable extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('addressable');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notblank' => true,
             'length' => 255,
             ));
        $this->hasColumn('address', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('postalcode', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));
        $this->hasColumn('city', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('country', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'email' => true,
             'length' => 255,
             ));
        $this->hasColumn('npai', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $geographical0 = new Doctrine_Template_Geographical();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->actAs($geographical0);
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}