<?php

/**
 * BaseProfessionalType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Professionals
 * 
 * @method string              getName()          Returns the current record's "name" value
 * @method Doctrine_Collection getProfessionals() Returns the current record's "Professionals" collection
 * @method ProfessionalType    setName()          Sets the current record's "name" value
 * @method ProfessionalType    setProfessionals() Sets the current record's "Professionals" collection
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProfessionalType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('professional_type');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notblank' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Professional as Professionals', array(
             'local' => 'id',
             'foreign' => 'professional_type_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}