<?php

/**
 * BasePhonenumber
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $number
 * 
 * @method string      getName()   Returns the current record's "name" value
 * @method string      getNumber() Returns the current record's "number" value
 * @method Phonenumber setName()   Sets the current record's "name" value
 * @method Phonenumber setNumber() Sets the current record's "number" value
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePhonenumber extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('phonenumber');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notblank' => true,
             'length' => 255,
             ));
        $this->hasColumn('number', 'string', 255, array(
             'type' => 'string',
             'notblank' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}