<?php

/**
 * BaseGroupDetail
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $group_id
 * @property string $information
 * @property Group $Group
 * 
 * @method integer     getGroupId()     Returns the current record's "group_id" value
 * @method string      getInformation() Returns the current record's "information" value
 * @method Group       getGroup()       Returns the current record's "Group" value
 * @method GroupDetail setGroupId()     Sets the current record's "group_id" value
 * @method GroupDetail setInformation() Sets the current record's "information" value
 * @method GroupDetail setGroup()       Sets the current record's "Group" value
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGroupDetail extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('group_detail');
        $this->hasColumn('group_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('information', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Group', array(
             'local' => 'group_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}