<?php

/**
 * BasePriceManifestation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $manifestation_id
 * @property integer $price_id
 * @property decimal $value
 * @property Manifestation $Manifestation
 * @property Price $Price
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Baptiste SIMON <baptiste.simon AT e-glop.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePriceManifestation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('price_manifestation');
        $this->hasColumn('manifestation_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('price_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('value', 'decimal', 8, array(
             'type' => 'decimal',
             'scale' => 3,
             'length' => 8,
             ));


        $this->index('manif_price', array(
             'fields' => 
             array(
              0 => 'manifestation_id',
              1 => 'price_id',
             ),
             'unique' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Manifestation', array(
             'local' => 'manifestation_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('Price', array(
             'local' => 'price_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}