<?php

/**
 * BasePrice
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property decimal $value
 * @property boolean $online
 * @property Doctrine_Collection $Manifestations
 * @property Doctrine_Collection $PriceManifestations
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Baptiste SIMON <baptiste.simon AT e-glop.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePrice extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('price');
        $this->hasColumn('name', 'string', 63, array(
             'type' => 'string',
             'notnull' => true,
             'notblank' => true,
             'length' => 63,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('value', 'decimal', 8, array(
             'type' => 'decimal',
             'scale' => 3,
             'length' => 8,
             ));
        $this->hasColumn('online', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Manifestation as Manifestations', array(
             'refClass' => 'PriceManifestation',
             'local' => 'price_id',
             'foreign' => 'manifestation_id'));

        $this->hasMany('PriceManifestation as PriceManifestations', array(
             'local' => 'id',
             'foreign' => 'price_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}