generator:
  class: sfDoctrineGenerator
  param:
    model_class:           OrganismCategory
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          organism_category
    with_doctrine_route:   true
    actions_base_class:    sfActions
    
    config:
      actions: ~
      fields:  ~
      list:
        display: [name]
        sort: [name, '']
        object_actions:
          _edit: ~
          _delete: ~
      filter:
        display: [name]
      form:
        display: [name]
      edit:
        title: Organism category "%%name%%"
      new:
        title: New organism category
