#**********************************************************************************
#
#	    This file is part of e-venement.
# 
#    e-venement is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License.
# 
#    e-venement is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
# 
#    You should have received a copy of the GNU General Public License
#    along with e-venement; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
# 
#    Copyright (c) 2006-2011 Baptiste SIMON <baptiste.simon AT e-glop.net>
#    Copyright (c) 2006-2011 Libre Informatique [http://www.libre-informatique.fr/]
# 
#**********************************************************************************/

Group:
  package: group
  tableName: group_table
  actAs:
    Timestampable: ~
    #Sluggable:
    #  fields: [name, sf_guard_user_id]
  columns:
    name:
      type: string(255)
      notblank: true
      notnull: true
    sf_guard_user_id: integer
    description: string
    slug: string
    picture_id:
      type: integer
      unique: true
    display_everywhere:
      type: boolean
      default: false
      notnull: true
  indexes:
    name_user:
      fields: [name, sf_guard_user_id]
      type: unique
  relations:
    Contacts:
      class: Contact
      refClass: GroupContact
      foreignAlias: Groups
    Professionals:
      class: Professional
      refClass: GroupProfessional
      foreignAlias: Groups
    Organisms:
      class: Organism
      refClass: GroupOrganism
      foreignAlias: Groups
    User:
      class: sfGuardUser
      foreignAlias: Groups
      onDelete: CASCADE
      onUpdate: CASCADE
    Users:
      class: sfGuardUser
      refClass: GroupUser
      foreignAlias: AuthForGroups
    Picture:
      foreignAlias: Groups
      onDelete: SET NULL
      onUpdate: CASCADE
GroupDetail:
  package: group
  actAs: [Timestampable]
  columns:
    group_id:
      type: integer
      notnull: true
      primary: true
    information: string
  relations:
    Group:
      foreignAlias: Members
      onDelete: CASCADE
      onUpdate: CASCADE
GroupContact:
  package: group
  inheritance:
    extends: GroupDetail
    type: concrete
  columns:
    contact_id:
      type: integer
      notnull: true
      primary: true
  relations:
    Contact:
      foreignAlias: ContactGroups
      onDelete: CASCADE
      onUpdate: CASCADE
    Group:
      foreignAlias: ContactGroups
      onDelete: CASCADE
      onUpdate: CASCADE
GroupProfessional:
  package: group
  inheritance:
    extends: GroupDetail
    type: concrete
  columns:
    professional_id:
      type: integer
      notnull: true
      primary: true
  relations:
    Professional:
      foreignAlias: ProfessionalGroups
      onDelete: CASCADE
      onUpdate: CASCADE
    Group:
      foreignAlias: ProfessionalGroups
      onDelete: CASCADE
      onUpdate: CASCADE
GroupOrganism:
  package: group
  inheritance:
    extends: GroupDetail
    type: concrete
  columns:
    organism_id:
      type: integer
      notnull: true
      primary: true
  relations:
    Organism:
      foreignAlias: OrganismGroups
      onDelete: CASCADE
      onUpdate: CASCADE
    Group:
      foreignAlias: OrganismGroups
      onDelete: CASCADE
      onUpdate: CASCADE
GroupUser:
  package: group
  inheritance:
    extends: GroupDetail
    type: concrete
  columns:
    sf_guard_user_id:
      type: integer
      notnull: true
      primary: true
  relations:
    User:
      foreignAlias: UserGroups
      onDelete: CASCADE
      onUpdate: CASCADE
    Group:
      foreignAlias: UserGroups
      onDelete: CASCADE
      onUpdate: CASCADE
GroupDeleted:
  package: group
  inheritance:
    extends: GroupDetail
    type: concrete
  columns:
  relations:
    Group:
      foreignAlias: UserGroups
      onDelete: CASCADE
      onUpdate: CASCADE
