#**********************************************************************************
#
#	    This file is part of e-venement.
# 
#    e-venement is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License.
# 
#    e-venement is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
# 
#    You should have received a copy of the GNU General Public License
#    along with e-venement; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
# 
#    Copyright (c) 2006-2011 Baptiste SIMON <baptiste.simon AT e-glop.net>
#    Copyright (c) 2011 Ayoub HIDRI <ayoub.hidri AT gmail.com>
#    Copyright (c) 2006-2011 Libre Informatique [http://www.libre-informatique.fr/]
# 
#**********************************************************************************/

ContactEntry:
  package: grp
  actAs:
    Timestampable: ~
  indexes:
    contact_entry_confirmed_idx:
      fields: [confirmed]
  columns:
    professional_id:
      type: integer
      notnull: true
    comment1: string
    comment2: string
    confirmed: boolean
    entry_id:
      type: integer
      notnull: true
    transaction_id: integer
  relations:
    Professional:
      foreignAlias: ContactEntries
      onUpdate: CASCADE
      onDelete: CASCADE
    Entry:
      foreignAlias: ContactEntries
      onUpdate: CASCADE
      onDelete: CASCADE
    Transaction:
      foreignAlias: Entries
      onUpdate: CASCADE
      onDelete: SET NULL
  indexes:
    contact_entry_index_idx:
      fields: [professional_id,entry_id]
      unique: true

ManifestationEntry:
  package: grp
  actAs:
    Timestampable: ~
  columns:
    manifestation_id:
      type: integer
      notnull: true
    entry_id:
      type: integer
      notnull: true
  relations:
    Manifestation:
      foreignAlias: ManifestationEntries
      onUpdate: CASCADE
      onDelete: CASCADE
    Entry:
      foreignAlias: ManifestationEntries
      onUpdate: CASCADE
      onDelete: CASCADE
  indexes:
    manif_entry_index_idx:
      fields: [manifestation_id,entry_id]
      unique: true

Entry:
  package: grp
  actAs:
    Timestampable: ~
  columns:
    event_id:
      type: integer
      notnull: true
      unique: true
  relations:
    Event:
      foreignAlias: Entries
      onUpdate: CASCADE
      onDelete: CASCADE

EntryElement:
  package: grp
  actAs:
    Timestampable: ~
  indexes:
    entry_element_second_choice_idx:
      fields: [second_choice]
    entry_element_accepted_idx:
      fields: [accepted]
  columns:
    manifestation_entry_id:
      type: integer
      notnull: true
    contact_entry_id:
      type: integer
      notnull: true
    second_choice:
      type: boolean
      notnull: true
      default: false
    accepted:
      type: boolean
      notnull: true
      default: false
  relations:
    ContactEntry:
      foreignAlias: Entries
      onUpdate: CASCADE
      onDelete: CASCADE
    ManifestationEntry:
      foreignAlias: Entries
      onUpdate: CASCADE
      onDelete: CASCADE

EntryTickets:
  package: grp
  actAs:
    Timestampable: ~
  columns:
    entry_element_id:
      type: integer
      notnull: true
    price_id:
      type: integer
      notnull: true
    quantity:
      type: integer
      notnull: true
    gauge_id:
      type: integer
      notnull: true
  relations:
    EntryElement:
      foreignAlias: EntryTickets
      onUpdate: CASCADE
      onDelete: CASCADE
    Price:
      foreignAlias: EntryTickets
      onUpdate: CASCADE
      onDelete: CASCADE
    Gauge:
      foreignAlias: EntryTickets
      onUpdate: CASCADE
      onDelete: CASCADE
  indexes:
    entry_price_index_idx:
      fields: [entry_element_id,price_id]
      unique: true

GroupWorkspace:
  package: grp
  columns:
    workspace_id:
      type: integer
      notnull: true
      unique: true
  relations:
    Workspace:
      foreignAlias: GroupWorkspace
      onUpdate: CASCADE
      onDelete: CASCADE

