#**********************************************************************************
#
#	    This file is part of e-venement.
# 
#    e-venement is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License.
# 
#    e-venement is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
# 
#    You should have received a copy of the GNU General Public License
#    along with e-venement; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
# 
#    Copyright (c) 2006-2011 Baptiste SIMON <baptiste.simon AT e-glop.net>
#    Copyright (c) 2006-2011 Libre Informatique [http://www.libre-informatique.fr/]
# 
#**********************************************************************************/

MemberCard:
  package: mc
  inheritance:
    extends: Traceable
    type: concrete
  columns:
    name:
      type: string(255)
      notnull: true
      notblank: true
    contact_id:
      type: integer
      notnull: true
    expire_at:
      type: timestamp
      notnull: true
    active:
      type: boolean
      notnull: true
      default: true
  relations:
    Contact:
      foreignAlias: MemberCards
      onDelete: CASCADE
      onUpdate: CASCADE
MemberCardPrice:
  package: mc
  inheritance:
    extends: Traceable
    type: concrete
  columns:
    member_card_id:
      type: integer
      notnull: true
    price_id:
      type: integer
      notnull: true
    event_id: integer
  relations:
    MemberCard:
      foreignAlias: MemberCardPrices
      onDelete: CASCADE
      onUpdate: CASCADE
    Price:
      foreignAlias: MemberCardPrices
      onDelete: CASCADE
      onUpdate: CASCADE
    Event:
      foreignAlias: MemberCardPrices
      onDelete: CASCADE
      onUpdate: CASCADE
MemberCardPriceModel:
  package: mc
  inheritance:
    extends: Traceable
    type: concrete
  columns:
    member_card_name:
      type: string(255)
      notnull: true
      notblank: true
    price_id:
      type: integer
      notnull: true
    quantity:
      type: integer
      notnull: true
    event_id: integer
  relations:
    Price:
      foreignAlias: MemberCardPriceModel
      onDelete: CASCADE
      onUpdate: CASCADE
    Event:
      foreignAlias: MemberCardPriceModel
      onDelete: CASCADE
      onUpdate: CASCADE
  indexes:
    member_card_name_price_id_event_id:
      fields: [member_card_name, price_id, event_id]
      unique: true

