#**********************************************************************************
#
#	    This file is part of e-venement.
# 
#    e-venement is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License.
# 
#    e-venement is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
# 
#    You should have received a copy of the GNU General Public License
#    along with e-venement; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
# 
#    Copyright (c) 2006-2011 Baptiste SIMON <baptiste.simon AT e-glop.net>
#    Copyright (c) 2006-2011 Libre Informatique [http://www.libre-informatique.fr/]
# 
#**********************************************************************************/

MemberCardType:
  package: mc
  columns:
    name:
      type: string(255)
      unique: true
      notnull: true
      notblank: true
    description: string(255)
    value:
      type: integer
      notnull: true
  relations:
    Users:
      class: sfGuardUser
      refClass: MemberCardTypeUser
      foreignAlias: MemberCards
      local: member_card_type_id
      foreign: sf_guard_user_id
MemberCardTypeUser:
  package: mc
  columns:
    sf_guard_user_id:
      type: integer
      notnull: true
      primary: true
    member_card_type_id:
      type: integer
      notnull: true
      primary: true
MemberCard:
  package: mc
  inheritance:
    extends: Traceable
    type: concrete
  indexes:
    member_card_expire_at_idx:
      fields: [expire_at]
    member_card_active_idx:
      fields: [active]
  columns:
    contact_id: integer
    expire_at:
      type: timestamp
      notnull: true
    active:
      type: boolean
      notnull: true
      default: true
    member_card_type_id:
      type: integer
      notnull: true
    transaction_id: integer
  relations:
    Contact:
      foreignAlias: MemberCards
      onDelete: SET NULL
      onUpdate: CASCADE
    MemberCardType:
      foreignAlias: MemberCards
      onDelete: RESTRICT
      onUpdate: CASCADE
    Transaction:
      foreignAlias: MemberCards
      onDelete: RESTRICT
      onUpdate: CASCADE
MemberCardPrice:
  package: mc
  inheritance:
    extends: Traceable
    type: concrete
  columns:
    member_card_id:
      type: integer
      notnull: true
    price_id:
      type: integer
      notnull: true
    event_id: integer
  relations:
    MemberCard:
      foreignAlias: MemberCardPrices
      onDelete: CASCADE
      onUpdate: CASCADE
    Price:
      foreignAlias: MemberCardPrices
      onDelete: CASCADE
      onUpdate: CASCADE
    Event:
      foreignAlias: MemberCardPrices
      onDelete: CASCADE
      onUpdate: CASCADE
MemberCardPriceModel:
  package: mc
  inheritance:
    extends: Traceable
    type: concrete
  indexes:
    member_card_type_id_price_id_event_id_idx:
      fields: [member_card_type_id, price_id, event_id]
      unique: true
  columns:
    member_card_type_id:
      type: integer
      notnull: true
    price_id:
      type: integer
      notnull: true
    quantity:
      type: integer
      notnull: true
    event_id: integer
  relations:
    Price:
      foreignAlias: MemberCardPriceModels
      onDelete: CASCADE
      onUpdate: CASCADE
    Event:
      foreignAlias: MemberCardPriceModels
      onDelete: CASCADE
      onUpdate: CASCADE
    MemberCardType:
      foreignAlias: MemberCardPriceModels
      onDelete: RESTRICT
      onUpdate: CASCADE
