#**********************************************************************************
#
#	    This file is part of e-venement.
# 
#    e-venement is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License.
# 
#    e-venement is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
# 
#    You should have received a copy of the GNU General Public License
#    along with e-venement; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
# 
#    Copyright (c) 2006-2014 Baptiste SIMON <baptiste.simon AT e-glop.net>
#    Copyright (c) 2006-2014 Libre Informatique [http://www.libre-informatique.fr/]
# 
#**********************************************************************************/
ProductCategory:
  package: pos
  actAs:
    Timestampable: ~
    I18n:
      fields: [name]
    Sluggable:
      fields: [name]
    Searchable:
      fields: [name]
  columns:
    name:
      type:     string(255)
      notblank: true
      notnull:  true
      unique:   true
    vat_id: integer
Product:
  package: pos
  actAs:
    I18n:
      fields: [name, description]
    Sluggable:
      fields: [name]
    Searchable:
      fields: [name]
  inheritance:
    extends: Traceable
    type: concrete
  columns:
    name:
      type:     string(255)
      notblank: true
      notnull:  true
    meta_event_id: integer
    product_category_id: integer
    description: string
    picture_id:
      type: integer
      unique: true
    accounting_account: string(50)
  relations:
    Category:
      class: ProductCategory
      foreignAlias: Products
      onDelete: RESTRICT
      onUpdate: CASCADE
    MetaEvent:
      foreignAlias: Products
      onDelete: SET NULL
      onUpdate: CASCADE
    Picture:
      foreignType: one
      onDelete: SET NULL
      onUpdate: CASCADE
