#**********************************************************************************
#
#	    This file is part of e-venement.
# 
#    e-venement is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License.
# 
#    e-venement is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
# 
#    You should have received a copy of the GNU General Public License
#    along with e-venement; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
# 
#    Copyright (c) 2006-2011 Baptiste SIMON <baptiste.simon AT e-glop.net>
#    Copyright (c) 2006-2011 Libre Informatique [http://www.libre-informatique.fr/]
# 
#**********************************************************************************/

Traceable:
  package: tck
  actAs:
    Timestampable: ~
    Versionable:
      versionColumn: version
      className: %CLASS%Version
      auditLog: true
  columns:
    sf_guard_user_id:
      type: integer
      notnull: true
  relations:
    User:
      class: sfGuardUser
      foreignAlias: %CLASS%s
      onDelete: RESTRICT
      onUpdate: CASCADE

Transaction:
  package: tck
  inheritance:
    extends: Traceable
    type: concrete
  columns:
    contact_id: integer
    professional_id: integer
    transaction_id: integer
    type:
      type: enum
      values: [normal, cancellation, deposit]
      default: normal
      notnull: true
    closed:
      type: boolean
      default: false
      notnull: true
    workspace_id:
      type: integer
  relations:
    Contact:
      foreignAlias: Transactions
      onDelete: CASCADE
      onUpdate: CASCADE
    Professional:
      foreignAlias: Transactions
      onDelete: SET NULL
      onUpdate: CASCADE
    Transaction:
      foreignAlias: Translinked
      onDelete: SET NULL
      onUpdate: CASCADE
    Workspace:
      foreignAlias: Transactions
      onDelete: SET NULL
      onUpdate: CASCADE
Ticket:
  package: tck
  inheritance:
    extends: Traceable
    type: concrete
  columns:
    transaction_id:
      type: integer
      notnull: true
    manifestation_id:
      type: integer
      notnull: true
    gauge_id: integer
    price_id:
      type: integer
      notnull: true
    price_name:
      type: string(63)
      notnull: true
      notblank: true
    value:
      type: decimal(8)
      scale: 3
      notnull: true
    numerotation: string(255)
    duplicate: integer
    cancelling:
      type: integer
      unique: true
    printed:
      type: boolean
      default: false
      notnull: true
    integrated:
      type: boolean
      default: false
      notnull: true
    barcode: string(255)
    othercode: string(255)
  indexes:
    manif_numerotation:
      fields: [numerotation, manifestation_id]
      unique: true
    barcode:
      fields: [barcode]
    othercode:
      fields: [othercode]
  relations:
    Manifestation:
      foreignAlias: Tickets
      onDelete: RESTRICT
      onUpdate: CASCADE
    Transaction:
      foreignAlias: Tickets
      onDelete: RESTRICT
      onUpdate: CASCADE
    Price:
      foreignAlias: Tickets
      onDelete: RESTRICT
      onUpdate: CASCADE
    Duplicata:
      local: duplicate
      foreignAlias: Duplicated
      class: Ticket
      onDelete: SET NULL
      onUpdate: CASCADE
    Cancelled:
      local: cancelling
      foreignAlias: Cancelling
      class: Ticket
      onDelete: SET NULL
      onUpdate: CASCADE
    User:
      class: sfGuardUser
      foreignAlias: Tickets
      onDelete: RESTRICT
      onUpdate: CASCADE
    Gauge:
      foreignAlias: Tickets
      onDelete: RESTRICT
      onUpdate: CASCADE
Cancellation:
  package: tck
  inheritance:
    extends: Traceable
    type: concrete
  columns:
    transaction_id:
      type: integer
      notnull: true
    ticket_id:
      type: integer
      notnull: true
      unique: true
  relations:
    Ticket:
      foreignAlias: Cancellation
      onDelete: RESTRICT
      onUpdate: CASCADE
Control:
  package: tck
  inheritance:
    extends: Traceable
    type: concrete
  columns:
    ticket_id:
      type: integer
      notnull: true
    checkpoint_id:
      type: integer
      notnull: true
    comment: text
  relations:
    Ticket:
      foreignAlias: Controls
      onDelete: CASCADE
      onUpdate: CASCADE
    Checkpoint:
      foreignAlias: Controls
      onDelete: CASCADE
      onUpdate: CASCADE

Accounting:
  package: tck
  inheritance:
    extends: Traceable
    type: concrete
  columns:
    transaction_id:
      type: integer
      notnull: true
    type:
      type: string(255)
      notblank: true
      notnull: true
    manifestation_id: integer
  indexes:
    transaction_type:
      fields: [transaction_id, type, manifestation_id]
      type: unique
  relations:
    Transaction:
      foreignAlias: Accountings
      onDelete: CASCADE
      onUpdate: CASCADE
    Manifestation:
      foreignAlias: Accountings
      onDelete: CASCADE
      onUpdate: CASCADE
Order:
  package: tck
  inheritance:
    extends: Accounting
    type: column_aggregation
    keyField: type
    keyValue: 'order'
  relations:
    Transaction:
      foreignAlias: Order
      onDelete: CASCADE
      onUpdate: CASCADE
Invoice:
  package: tck
  inheritance:
    extends: Accounting
    type: column_aggregation
    keyField: type
    keyValue: 'invoice'    
  relations:
    Transaction:
      foreignAlias: Invoice
      onDelete: CASCADE
      onUpdate: CASCADE
RawAccounting:
  package: tck
  inheritance:
    extends: Traceable
    type: concrete
  columns:
    accounting_id:
      type: integer
      notnull: true
    content:
      type: string
      notnull: true
      notblank: true
  relations:
    Accounting:
      foreignAlias: RawAccountings
      onDelete: SET NULL
      onUpdate: CASCADE

PaymentMethod:
  package: tck
  columns:
    name:
      type: string(255)
      notblank: true
      notnull: true
    account: string(63)
    display:
      type: boolean
      notnull: true
      default: true
Payment:
  package: tck
  inheritance:
    extends: Traceable
    type: concrete
  columns:
    transaction_id:
      type: integer
      notnull: true
    payment_method_id:
      type: integer
      notnull: true
    value:
      type: decimal(8)
      scale: 3
      notnull: true
  relations:
    Transaction:
      foreignAlias: Payments
      onDelete: CASCADE
      onUpdate: CASCADE
    Method:
      class: PaymentMethod
      foreignAlias: Payments
      onDelete: RESTRICT
      onUpdate: CASCADE

ContactEventArchives:
  package: tck
  columns:
    contact_id:
      type: integer
      notnull: true
    happens_at:
      type: timestamp
      notnull: true
    name:
      type: string
      notnull: true
  relations:
    Contact:
      foreignAlias: EventArchives
      onDelete: CASCADE
      onUpdate: CASCADE
