#**********************************************************************************
#
#	    This file is part of e-venement.
# 
#    e-venement is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License.
# 
#    e-venement is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
# 
#    You should have received a copy of the GNU General Public License
#    along with e-venement; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
# 
#    Copyright (c) 2006-2011 Baptiste SIMON <baptiste.simon AT e-glop.net>
#    Copyright (c) 2006-2011 Libre Informatique [http://www.libre-informatique.fr/]
# 
#**********************************************************************************/

AutoGroup:
  package: ws
  columns:
    group_id:
      type: integer
      notnull: true
  relations:
    Group:
      class: Group
      foreignAlias: Online
      onDelete: CASCADE
      onUpdate: CASCADE

RemoteAuthentication:
  package: ws
  actAs:
    Timestampable: ~
  columns:
    sf_guard_user_id:
      type: integer
      notnull: true
    ipaddress:
      type: string(255)
      notnull: true
      notblank: true
    active:
      type: boolean
      notnull: true
      default: true
    salt:
      type: string(255)
      notnull: true
      notblank: true
  indexes:
    user_ipaddress_idx:
      fields: [sf_guard_user_id, ipaddress]
      type: unique
  relations:
    User:
      class: sfGuardUser
      foreignAlias: Groups
      onDelete: CASCADE
      onUpdate: CASCADE

BankPayment:
  package: ws
  actAs:
    Timestampable: ~
  columns:
    payment_id: integer
    serialized: string
    code: string(255)
    error: string
    merchant_id: string(255)
    merchant_country: string(255)
    amount: string(255)
    transaction_id: string(255)
    payment_means: string
    transmission_date: string(255)
    payment_time: string(255)
    payment_certificate: string(255)
    authorization_id: string(255)
    currency_code: string(255)
    card_number: string(255)
    cvv_flag: string(255)
    bank_response_code: string(255)
    complementary_code: string(255)
    complementary_info: string(255)
    return_context: string(255)
    caddie: string
    receipt_complement: string
    merchant_language: string(255)
    language: string(255)
    customer_id: string(255)
    order_id: string(255)
    customer_email: string(255)
    customer_ip_address: string(255)
    capture_day: string(255)
    capture_mode: string(255)
    data_field: string(255)
    cvv_response_code: string(255)
    payment_date: string(255)
    response_code: string(255)
    raw: string

Survey:
  package: ws
  inheritance:
    extends: Traceable
    type: concrete
  columns:
    name:
      type: string(255)
      notblank: true
      notnull: true
SurveyQuery:
  package: ws
  actAs:
    I18N:
      fields: [name]
  inheritance:
    extends: Traceable
    type: concrete
  columns:
    name:
      type: string
      notblank: true
      notnull: true
    survey_id:
      type: integer
      notnull: true
    type:
      type: string(255)
      notnull: true
      notblank: true
    multiple:
      type: boolean
      default: false
      notnull: true
    weight:
      type: integer
      notnull: true
      default: 1
  Relations:
    Survey:
      foreignAlias: Queries
      onDelete: CASCADE
      onUpdate: CASCADE
SurveyAnswer:
  package: ws
  inheritance:
    extends: Traceable
    type: concrete
  columns:
    survey_query_id:
      type: integer
      notnull: true
    lang:
      type: string(255)
      notnull: true
      notblank: true
    value:
      type: string
      notnull: true
  Relations:
    Query:
      class: SurveyQuery
      foreignAlias: Answers
      onDelete: RESTRICT
      onUpdate: CASCADE
SurveyApplyTo:
  package: ws
  columns:
    survey_id:
      type: integer
      notnull: true
    date_from: datetime
    date_to: datetime
    manifestation_id: integer
    everywhere:
      type: boolean
      default: false
      notnull: true
  Relations:
    Query:
      class: SurveyQuery
      foreignAlias: Answers
      onDelete: RESTRICT
      onUpdate: CASCADE
    Manifestation:
      foreignAlias: Surveys
      onDelete: SETNULL
      onUpdate: CASCADE
