generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Transaction
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          transaction_transactionsList
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        list_first_user: { label: Created by }
        list_professional: { label: Organism }
        transaction_id: { label: Linked transactions }
        list_contact: { label: Contact }
        sf_guard_user_id: { label: User }
        list_details: { label: Details }
        list_payments_list: { label: Payments }
        list_order: { label: Order }
        list_invoice: { label: Invoice }
        list_price: { label: Total }
        empty: { label: Empty? }
      list:
        actions:
          _new:
            credentials: [tck-transaction]
        batch_actions:
          _printTickets:
            label: Print tickets
            credentials: [tck-print-ticket]
        object_actions:
          _showUp:
            action: show
            label: Show up
        title: Transactions
        display: [id, _list_id, closed, _list_payments_list, _list_price, _list_contact, _list_professional, transaction_id, _list_transaction_id, _list_order, _list_invoice, created_at, _list_first_user, updated_at, User, _list_details]
        sort: [id, desc]
        max_per_page: 50
      filter:
        display:
          Internals:
            [closed, created_at, created_by, updated_at, sf_guard_user_id, transaction_id]
          Externals:
            [contact_id, organism_id, manifestation_id, hold_id, print_state]
      form:    ~
      edit:    ~
      new:     ~
