generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Professional
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          professional_full
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        name: { label: Function }
        groups_picto: { label: Remarkable }
        professional_id: { label: Contact }
      list:
        display: [Contact, _groups_picto, name, Organism, contact_email]
        batch_actions: {}
        object_actions: { _edit: ~ }
        table_method: doSelectOnlyGrp
        title: By contact
      filter:
        display: [contact_name, organism_name, professional_type_id, organism_id, groups_list]
      form:    ~
      edit:    ~
      new:
        title: New Entry
        display: [professional_id, event_id]
        actions:
          _list: ~
          _save: ~
