all:
  credentials: [tck-transaction]
cancelBoot:
  credentials: [tck-cancel]
cancel:
  credentials: [tck-cancel]
print:
  credentials: [tck-print-ticket]
duplicate:
  credentials: [tck-print-ticket]
control:
  credentials: [tck-control]
order:
  credentials: [tck-accounting-order]
invoice:
  credentials: [tck-accounting-invoice]
