default:
  javascripts: [jquery,menu]

printSuccess:
  javascripts: [-*, jquery, print-tickets]
  stylesheets: [-*, print-tickets.default: {media: all}]
orderSuccess:
  javascripts: [-*, jquery, print-ticket]
  stylesheets: [-*, print-accounting: {media: all}, /private/print-accounting.css: {media: all}]
invoiceSuccess:
  javascripts: [-*, jquery, print-ticket]
  stylesheets: [-*, print-accounting: {media: all}, /private/print-accounting.css: {media: all}]

gaugeSuccess:
  stylesheets: [gauge]
sellSuccess:
  javascripts: [/private/ticket.js]

failedSuccess:
  stylesheets: [ticket]
passedSuccess:
  stylesheets: [ticket]
controlSuccess:
  stylesheets: [ticket]

cancelSuccess:
  stylesheets: [ticket-cancel]
cancelBootSuccess:
  stylesheets: [ticket-cancel]
canceledTicketSuccess:
  stylesheets: [ticket]
