#**********************************************************************************
#
#	    This file is part of e-venement.
# 
#    e-venement is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License.
# 
#    e-venement is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
# 
#    You should have received a copy of the GNU General Public License
#    along with e-venement; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
# 
#    Copyright (c) 2006-2014 Baptiste SIMON <baptiste.simon AT e-glop.net>
#    Copyright (c) 2011 Ayoub HIDRI <ayoub.hidri AT gmail.com>
#    Copyright (c) 2006-2014 Libre Informatique [http://www.libre-informatique.fr/]
# 
#**********************************************************************************/

Dummy:
    package: generic
Addressable:
  package: generic
  actAs: 
    Searchable:
      fields: [name]
    Sluggable:
      unique: true
      fields: [name]
    Timestampable: ~
    Versionable:
      versionColumn: version
      className: %CLASS%Version
      auditLog: true
  indexes:
    %CLASS%_postalcode_idx:
      fields: [postalcode]
    %CLASS%_country_idx:
      fields: [country]
    %CLASS%_npai_idx:
      fields: [npai]
    %CLASS%_email_no_newsletter_idx:
      fields: [email_no_newsletter]
    %CLASS%_vcard_uid_idx:
      fields: [vcard_uid]
  columns:
    name:
      type: string(255)
      notblank: true
      notnull: true
    address: string
    postalcode: string(10)
    city: string(255)
    country:
      default: FRANCE
      type: string(255)
    email:
      type: string(255)
      email: true
    email_no_newsletter:
      type: boolean
      notnull: true
      default: false
    email_npai:
      type: boolean
      notnull: true
      default: false
    npai:
      type: boolean
      notnull: true
      default: false
    no_mailing:
      type: boolean
      notnull: true
      default: false
    vcard_uid:
      type: string(255)
      unique: true
    last_accessor_id: integer
    automatic:
      type: boolean
      notnull: true
      default: false
  relations:
    LastAccessor:
      local: last_accessor_id
      class: sfGuardUser
      foreignAlias: %CLASS%s
      onDelete: RESTRICT
      onUpdate: CASCADE

Postalcode:
  package: generic
  indexes:
    postalcode_postalcode_idx:
      fields: [postalcode]
  columns:
    insee:
      type: string(7)
      notnull: true
      notblank: true
    postalcode:
      type: string(7)
      notnull: true
      notblank: true
    city:
      type: string(255)
      notnull: true
      notblank: true

Country:
  package: generic
  actAs:
    I18n:
      fields: [name, nationality]
  columns:
    name:
      type: string(255)
      notnull: true
      notblank: true
    nationality:
      type: string(255)
    codeiso2:
      type: string(2)

Traceable:
  package: generic
  actAs:
    Timestampable: ~
    Versionable:
      versionColumn: version
      className: %CLASS%Version
      auditLog: true
  indexes:
    %CLASS%_updated_at_idx:
      fields: [updated_at]
    %CLASS%_created_at_idx:
      fields: [created_at]
  columns:
    sf_guard_user_id: integer
    automatic:
      type: boolean
      notnull: true
      default: false
  relations:
    User:
      class: sfGuardUser
      foreignAlias: %CLASS%s
      onDelete: RESTRICT
      onUpdate: CASCADE

Itemable: # items that can be sold
  package: generic
  inheritance:
    extends: Traceable
    type: concrete
  indexes:
    %CLASS%_transaction_id_idx:
      fields: [transaction_id]
  columns:
    transaction_id:
      type: integer
      notnull: true
    vat:
      type: decimal(5)
      scale: 4
      notnull: true
      default: 0
    value:
      type: decimal(8)
      scale: 3
      notnull: true
  relations:
    Transaction:
      foreignAlias: %CLASS%s
      onDelete: RESTRICT
      onUpdate: CASCADE

Phonenumber:
  package: generic
  actAs: [Timestampable]
  columns:
    name:
      type: string(255)
    number:
      type: string(255)
      notnull: true
      notblank: true

ModelType:
  package: generic
  actAs:
    Timestampable: ~
    Sluggable:
      fields: [type,name]
      unique: true
  columns:
    name:
      type: string(255)
    type:
      type: string(255)
      notblank: true
      notnull: true
  indexes:
    name_type_idx:
      fields: [name, type]
      type: unique

Option:
  package: generic
  tableName: option_table
  actAs:
    Timestampable:
      updated:
        disabled: true
  columns:
    type:
      type: string(255)
      notblank: true
      notnull: true
    sf_guard_user_id: integer
    name:
      type: string(255)
      notblank: true
      notnull: true
    value:
      type: string
      notnull: true
    domain:
      type: string
      notnull: true
      default: ''
  relations:
    sfGuardUser:
      foreignAlias: Options
      onDelete: CASCADE
  indexes:
    %CLASS%_name_user_value_type_idx:
      fields: [name, sf_guard_user_id, value, type, domain]
      type: unique

Authentication:
  package: generic
  actAs:
    Timestampable:
      updated:
        disabled: true
  columns:
    sf_guard_user_id: integer
    description: string
    ip_address:  string(255)
    user_agent:  string(255)
    referer:     string(255)
    server:      string(255)
    success:     boolean
  relations:
    User:
      class: sfGuardUser
      foreignAlias: Authentications
      onDelete: SET NULL
      onUpdate: CASCADE

Picture:
  package: generic
  actAs:
    Timestampable: ~
    Versionable: ~
  indexes:
    picture_type_idx:
      fields: [type]
  columns:
    name:
      type: string(255)
      notnull: true
      notblank: true
    type:
      type: string(255)
      notnull: true
      notblank: true
    content:
      type: blob
      notnull: true
    width: integer
    height: integer
    content_encoding: string(255)

Jabber:
  package: generic
  indexes:
    jabber_jabber_id_idx:
      fields: [jabber_id]
  columns:
    jabber_id:
      type: string(255)
      email: true
      notnull: true
    password:
      type: string(255)
      notnull: true
      notblank: true
    sf_guard_user_id:
      type: integer
      unique: true
      notnull: true
  relations:
    User:
      class: sfGuardUser
      foreignAlias: Jabber
      onDelete: CASCADE
      onUpdate: CASCADE

Filter:
  package: generic
  indexes:
    filter_name_idx:
      fields: [name]
    filter_type_idx:
      fields: [type]
    filter_name_type_user_id_idx:
      fields: [name, type, sf_guard_user_id]
      type: unique
  columns:
    sf_guard_user_id:
      type: integer
      notnull: true
    type:
      type: string(255)
      notnull: true
      notblank: true
    name:
      type: string(255)
      notnull: true
      notblank: true
    filter:
      type: text
      notnull: true
      notblank: true
  relations:
    User:
      class: sfGuardUser
      foreignAlias: Filters
      
Cache:
  package: generic
  actAs:
    Timestampable: ~
    Versionable: ~
  indexes:
    cache_domain_identifier_idx:
      fields: [domain, identifier]
      type: unique
  columns:
    content: blob
    domain: string(255)
    identifier: string(255)

Domain:
  package: generic
  indexes:
    domain_idx:
      fields: [name]
  columns:
    sf_guard_user_id:
      type: integer
      notnull: true
      unique: true
    name:
      type: string(255)
      notnull: true
  relations:
    User:
      class: sfGuardUser
      foreignAlias: Domain
      onDelete: CASCADE
      onUpdate: CASCADE

Color:
  package: generic
  actAs: [Timestampable]
  columns:
    name:
      type:     string(255)
      notnull:  true
      notblank: true
    color:
      type:     string(255)
      notnull:  true
      notblank: true
    target:
      type:     string(255)
      notnull:  true
      notblank: true
      default:  'manifestation'
    domain:
      type: string(255)
      notnull: true
      default: ''
