generator:
  class: sfDoctrineGenerator
  param:
    model_class:           MemberCard
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          member_card
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [name, Contact, expire_at]
      filter:
        display: [name, contact_id, expire_at]
      form:    ~
      edit:    ~
      new:     ~
