all:
  credentials: pr-card-view

create:  
  credentials: pr-card-mod
new:
  credentials: super-admin
edit:
  credentials: super-admin
update:
  credentials: super-admin
delete:
  credentials: pr-card-mod
