<?php

/**
 * Email
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Baptiste SIMON <baptiste.simon AT e-glop.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Email extends PluginEmail
{
  public $test = false;
  
  public function save(Doctrine_Connection $conn = null)
  {
    if ( $this->sent )
      return $this;
    
    if ( !$this->test )
    {
      // send email
      $sent = true;
      
      if ( $sent )
        $this->sent = true;
    }
    
    $this->updated_at = date('Y-m-d H:i:s');
    return parent::save($conn);
  }
}
