generator:
  class: sfDoctrineGenerator
  param:
    model_class:           order
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          order
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        sf_guard_user_id: { label: User }
      list:
        display: [_id,_transaction_id,created_at,User]
      filter:
        display: [transaction_id,created_at,sf_guard_user_id]
      form:    ~
      edit:    ~
      new:     ~
