config/project.yml:
  class:    sfDefineEnvironmentConfigHandler
  param:
    prefix:  project_
config/e-venement.yml:
  class:    sfDefineEnvironmentConfigHandler
  param:
    prefix:  software_
modules/*/config/tdp.yml:
  class: sfDefineEnvironmentConfigHandler
  param:
    prefix: tdp_
