generator:
  class: sfDoctrineGenerator
  param:
    model_class:           GroupWorkspace
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          group_workspace
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [Workspace]
        object_actions: { _edit: ~, _delete: ~ }
        title: Workspaces available for groups modules
      filter:  ~
      form:    ~
      edit:
        title: Workspace
      new:
        title: New workspace
