generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Control
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          control
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        list_manifestations: { label: Manifestation }
        sf_guard_user_id: { label: User }
      list:
        display: [_list_manifestations, checkpoint, created_at, comment, ticket_id, User]
        title: Flow display
      filter:
        display: [created_at, checkpoint_id, sf_guard_user_id, manifestation_id]
      form:    ~
      edit:    ~
      new:     ~
