generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Professional
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          professional
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        name: { label: Function }
        groups_picto: { label: Remarkable }
        nb_manifestations: { label: Manifs, type: numeric }
        nb_events: { label: Events, type: numeric }
        list_organism_administrative_number: { label: Admin.ID }
      list:
        display: [Contact, _groups_picto, name, Organism, contact_email, _list_organism_administrative_number, nb_events, nb_manifestations]
        batch_actions: {}
        actions:
          _extract: { action: extract }
        object_actions:
          _show: ~
          _edit:
            credentials: grp-events
        table_method: doSelectOnlyGrp
        title: By contact
        max_per_page: 50
      filter:
        display: [contact_name, organism_name, professional_type_id, organism_id, groups_list]
      form:    ~
      edit:
        actions: { _list: ~ }
      new:     ~
